#!/usr/bin/env python3
"""Validate D101 auto-anneal sparse-stabilization prep artifacts."""
from __future__ import annotations
import argparse, json, sys
from pathlib import Path
TASK="D101_AUTO_ANNEAL_AND_SPARSE_STABILIZATION_PREP"; D100_COMMIT="590995acdb9976812599b0fe2aa0f1fa7e7af1ea"
REPORTS="""d100_upstream_manifest.json d101_scale_report.json d101_component_schema_report.json d101_feature_path_importance_report.json d101_recurrent_state_importance_report.json d101_halting_head_importance_report.json d101_route_logit_head_importance_report.json d101_confidence_head_importance_report.json d101_convergence_path_importance_report.json d101_single_component_ablation_report.json d101_grouped_component_ablation_report.json d101_route_class_conditional_ablation_report.json d101_tail_only_ablation_report.json d101_min_seed_ablation_report.json d101_worst_seed_ablation_report.json d101_magnitude_rank_map_report.json d101_activation_usage_rank_map_report.json d101_hidden_state_delta_contribution_report.json d101_feature_permutation_sensitivity_report.json d101_redundant_component_coablation_report.json d101_protected_component_ablation_sentinel_report.json d101_shadow_mask_1pct_report.json d101_shadow_mask_3pct_report.json d101_shadow_mask_5pct_report.json d101_shadow_mask_8pct_report.json d101_shadow_mask_10pct_report.json d101_shadow_mask_reference_only_report.json d101_anneal_pressure_very_light_report.json d101_anneal_pressure_light_report.json d101_anneal_pressure_moderate_report.json d101_anneal_pressure_reference_only_report.json d101_route_aware_pressure_report.json d101_tail_protected_pressure_report.json d101_halting_protected_pressure_report.json d101_loop_utility_protected_pressure_report.json d101_sparsity_safety_frontier_report.json d101_recommended_d102_schedule_report.json d101_low_cost_ood_top1_ambiguity_tail_sparsity_report.json d101_combined_ood_joint_boundary_carryover_report.json d101_recurrent_loop_utility_sparsity_report.json d101_recurrent_convergence_sparsity_report.json d101_recurrent_halting_sparsity_report.json d101_recurrent_state_robustness_sparsity_report.json d101_safety_margin_sparsity_report.json d101_top1_guard_sparsity_report.json d101_D68_sparsity_report.json d101_oracle_distance_frontier_sparsity_report.json d101_support_cost_frontier_sparsity_report.json d101_label_shuffle_sentinel_report.json d101_regime_label_leak_sentinel_report.json d101_row_id_lookup_sentinel_report.json d101_python_hash_lookup_sentinel_report.json d101_file_order_artifact_sentinel_report.json d101_seed_id_shortcut_sentinel_report.json d101_hidden_state_label_leak_sentinel_report.json d101_hidden_state_row_lookup_sentinel_report.json d101_halt_step_shortcut_sentinel_report.json d101_step_count_shortcut_sentinel_report.json d101_mask_id_shortcut_sentinel_report.json d101_sparsity_pattern_shortcut_sentinel_report.json d101_split_integrity_report.json d101_overfit_memorization_report.json d101_negative_controls_report.json d101_truth_leak_oracle_isolation_report.json d101_rust_invocation_report.json d101_report_schema_metric_crosscheck_report.json d101_deterministic_replay_report.json aggregate_metrics.json decision.json summary.json report.md""".split()
def load(path:Path): return json.loads(path.read_text(encoding="utf-8"))
def fail(msg): print(f"D101 check failed: {msg}",file=sys.stderr); sys.exit(1)
def expect(cond,msg):
    if not cond: fail(msg)
def main():
    ap=argparse.ArgumentParser(description=__doc__); ap.add_argument("--out",type=Path,required=True); args=ap.parse_args(); out=args.out
    missing=[r for r in REPORTS if not (out/r).exists()]; expect(not missing,f"missing reports: {missing}")
    agg=load(out/"aggregate_metrics.json"); dec=load(out/"decision.json"); summ=load(out/"summary.json"); man=load(out/"d100_upstream_manifest.json"); m=agg["metrics"]; g=agg["positive_gates"]
    expect(agg["task"]==TASK,"aggregate task mismatch"); expect(man["requested_d100_commit"]==D100_COMMIT,"D100 commit mismatch")
    expect(man["artifact_present"] is True and man["validation_status"]=="passed","D100 handoff invalid")
    expect(man["replayed_decision"]=="d100_recurrent_routing_microcircuit_scale_confirmed","D100 decision mismatch")
    expect(man["replayed_next"]==TASK,"D100 next mismatch"); expect(man["replayed_best_fair_recurrent"]=="D99_RECURRENT_HALTING_CONFIDENCE_FAIR_SCALE","D100 arm mismatch")
    if not man.get("commit_present"): expect(man.get("restore_or_rerun_attempted") and man.get("restore_or_rerun_succeeded"),"missing D100 commit requires restore/rerun")
    expect(dec["decision"]=="d101_auto_anneal_sparse_stabilization_prep_ready","unexpected decision"); expect(dec["next"]=="D102_CONTROLLED_SPARSE_AUTO_ANNEAL_PROTOTYPE","unexpected next")
    expect(dec["recommended_safe_shadow_sparsity_pct"]==8,"unexpected sparsity recommendation"); expect(dec["recommended_safe_anneal_pressure"]=="light","unexpected pressure recommendation")
    expect(dec["failed_jobs"]==[] and dec["fallback_rows"]==0 and dec["scale_reduced"] is False,"failed/fallback/scale issue")
    expect(agg["scale"]["scale_reduced"] is False and agg["scale"]["all_required_stress_modes_executed"] is True,"scale gate issue")
    expect(all(g.values()),f"positive gates failed: {[k for k,v in g.items() if not v]}")
    for r in REPORTS:
        if r in {"d100_upstream_manifest.json","aggregate_metrics.json","decision.json","summary.json","report.md"}: continue
        expect(load(out/r).get("passed") is True,f"{r} not passed")
    expect(m["component_count"]>0 and m["protected_component_count"]>0 and m["candidate_redundant_component_count"]>0,"component map incomplete")
    for k,t in {"saliency_rank_stability":0.72,"importance_rank_cross_seed_stability":0.70,"tail_importance_rank_stability":0.70,"min_seed_importance_rank_stability":0.70,"protected_component_ablation_failure_rate":0.80,"redundant_component_mask_pass_rate":0.80}.items(): expect(m[k]>=t,f"{k} below threshold")
    base_min={"baseline_test_accuracy":0.9940,"baseline_ood_accuracy":0.9915,"baseline_stress_accuracy":0.9910,"baseline_min_seed_accuracy":0.9905,"baseline_worst_seed_accuracy":0.9895,"baseline_convergence_rate":0.998,"baseline_loop_usefulness_score":0.70,"baseline_loop_usefulness_on_tail_score":0.70,"baseline_state_stability_score":0.80,"baseline_low_cost_ood_top1_tail_score":0.746,"baseline_min_seed_low_cost_ood_top1_tail_score":0.742,"baseline_combined_ood_joint_boundary_breakpoint":0.755,"baseline_min_seed_combined_ood_joint_boundary_breakpoint":0.752}
    for k,t in base_min.items(): expect(m[k]>=t,f"{k} below threshold")
    for k,c in {"baseline_false_confidence_rate":0.0046,"baseline_non_convergence_rate":0.001,"baseline_oscillation_rate":0.001,"baseline_halting_false_positive_rate":0.0046}.items(): expect(m[k]<=c,f"{k} above ceiling")
    expect(m["baseline_routing_failure_rows"]==0 and m["baseline_D68_preservation_rate"]==1.0 and m["baseline_top1_guard_preserved"] and not m["baseline_top1_guard_weakened"],"baseline guard failure")
    for name in ["shadow_mask_1pct","shadow_mask_3pct","shadow_mask_5pct","shadow_mask_8pct"]: expect(m["shadow_masks"][name]["mask_passed_all_hard_gates"] and m["shadow_masks"][name]["mask_non_destructive"],f"{name} failed")
    hm=m["highest_recommended_shadow_mask_metrics"]; expect(hm["mask_pct"]==8 and hm["mask_passed_all_hard_gates"],"highest recommended mask invalid")
    expect(5<=m["recommended_safe_shadow_sparsity_pct"]<=10 and m["reference_only_masks_not_used_for_recommendation"],"shadow recommendation overclaim")
    p=m["anneal_pressure_probes"]; expect(p["very_light"]["pressure_passed_all_hard_gates"] and p["light"]["pressure_passed_all_hard_gates"],"core pressure probes failed")
    expect(any(p[x]["pressure_passed_all_hard_gates"] for x in ["route_aware","tail_protected","halting_protected","loop_utility_protected"]),"protected pressure probes failed")
    expect(m["recommended_d102_schedule_defined"] and m["d102_ready"] and m["recommended_d102_protected_components"] and m["recommended_d102_candidate_components"],"D102 schedule not ready")
    for key in ["label_shuffle_sentinel_accuracy","regime_label_leak_sentinel_accuracy","row_id_lookup_sentinel_accuracy","python_hash_lookup_sentinel_accuracy","file_order_artifact_sentinel_accuracy","seed_id_shortcut_sentinel_accuracy","hidden_state_label_leak_sentinel_accuracy","hidden_state_row_lookup_sentinel_accuracy","halt_step_shortcut_sentinel_accuracy","step_count_shortcut_sentinel_accuracy","mask_id_shortcut_sentinel_accuracy","sparsity_pattern_shortcut_sentinel_accuracy"]: expect(m[key]<=0.56,f"{key} shortcut too high")
    expect(not m["forbidden_feature_detected"] and not m["route_distillation_label_leak_risk"] and m["split_integrity_passed"] and not m["train_test_ood_contamination_detected"] and m["sentinel_collapse_passed"] and m["memorization_risk_score"]<=0.10,"leak/split/sentinel failure")
    expect(m["rust_path_invoked"] and m["fallback_rows"]==0 and m["failed_jobs"]==[] and m["deterministic_replay_passed"] and m["report_schema_consistency_passed"] and m["metric_crosscheck_passed"],"infrastructure failure")
    expect(summ["decision"]==dec["decision"] and summ["next"]==dec["next"],"summary mismatch")
    print(json.dumps({"status":"passed","artifact_path":str(out),"decision":dec["decision"],"next":dec["next"],"recommended_safe_shadow_sparsity_pct":m["recommended_safe_shadow_sparsity_pct"],"recommended_safe_anneal_pressure":m["recommended_safe_anneal_pressure"]},indent=2,sort_keys=True))
if __name__=="__main__": main()
