#!/usr/bin/env python3
"""Validate D104 sparse recurrent generalization frontier artifacts."""
from __future__ import annotations
import argparse, json
from pathlib import Path
TASK="D104_SPARSE_RECURRENT_GENERALIZATION_AND_COMPRESSION_FRONTIER_MAP"; D103_COMMIT="84290ac5e667b7acc35cd9beb2f15f239cc8acd1"
REPORTS="""d103_upstream_manifest.json d104_scale_report.json d104_family_set_report.json d104_sparse_candidate_identity_report.json d104_dense_baseline_generalization_reference_report.json d104_sparse_candidate_generalization_map_report.json d104_cross_family_transfer_report.json d104_heldout_family_report.json d104_family_shift_calibration_report.json d104_family_specific_loop_utility_report.json d104_family_specific_halting_report.json d104_family_specific_convergence_report.json d104_family_specific_mask_stability_report.json d104_family_specific_compression_report.json d104_family_specific_top1_guard_report.json d104_family_specific_D68_report.json d104_family_specific_safety_report.json d104_family_specific_rust_invocation_report.json d104_low_cost_ood_top1_ambiguity_transfer_report.json d104_combined_ood_joint_boundary_transfer_report.json d104_ood_support_shift_transfer_report.json d104_external_required_transfer_report.json d104_indistinguishable_abstain_transfer_report.json d104_correlated_echo_distractor_transfer_report.json d104_adversarial_counter_transfer_report.json d104_polynomial_symbolic_transfer_report.json d104_rational_symbolic_transfer_report.json d104_trig_periodic_symbolic_transfer_report.json d104_mixed_symbolic_transfer_report.json d104_compression_frontier_map_report.json d104_sparse_8pct_frontier_report.json d104_reference_only_oversparsity_report.json d104_sparse_mask_replay_report.json d104_sparse_checkpoint_replay_report.json d104_sparse_mask_stability_report.json d104_sparse_recovery_report.json d104_protected_component_integrity_report.json d104_candidate_component_stability_report.json d104_sparse_route_distribution_report.json d104_oracle_distance_frontier_report.json d104_support_cost_frontier_report.json d104_label_shuffle_sentinel_report.json d104_regime_label_leak_sentinel_report.json d104_family_label_leak_sentinel_report.json d104_row_id_lookup_sentinel_report.json d104_python_hash_lookup_sentinel_report.json d104_file_order_artifact_sentinel_report.json d104_seed_id_shortcut_sentinel_report.json d104_hidden_state_label_leak_sentinel_report.json d104_hidden_state_row_lookup_sentinel_report.json d104_hidden_state_family_leak_sentinel_report.json d104_halt_step_shortcut_sentinel_report.json d104_step_count_shortcut_sentinel_report.json d104_mask_id_shortcut_sentinel_report.json d104_sparsity_pattern_shortcut_sentinel_report.json d104_checkpoint_id_shortcut_sentinel_report.json d104_component_id_shortcut_sentinel_report.json d104_sparse_mask_replay_shortcut_sentinel_report.json d104_sparse_rust_path_shortcut_sentinel_report.json d104_family_router_shortcut_sentinel_report.json d104_split_integrity_report.json d104_overfit_memorization_report.json d104_negative_controls_report.json d104_truth_leak_oracle_isolation_report.json d104_report_schema_metric_crosscheck_report.json d104_deterministic_replay_report.json aggregate_metrics.json decision.json summary.json report.md""".split()
def load(p:Path): return json.loads(p.read_text(encoding="utf-8"))
def expect(c,msg):
    if not c: raise SystemExit(f"D104 check failed: {msg}")
def main():
    ap=argparse.ArgumentParser(); ap.add_argument("--out",type=Path,default=Path("target/pilot_wave/d104_sparse_recurrent_generalization_and_compression_frontier_map")); args=ap.parse_args(); out=args.out
    missing=[r for r in REPORTS if not (out/r).exists()]; expect(not missing,f"missing reports: {missing}")
    agg=load(out/"aggregate_metrics.json"); dec=load(out/"decision.json"); summ=load(out/"summary.json"); man=load(out/"d103_upstream_manifest.json"); m=agg["metrics"]; g=agg["positive_gates"]
    expect(agg["task"]==TASK,"task mismatch"); expect(man["requested_d103_commit"]==D103_COMMIT,"D103 commit mismatch")
    expect(man["artifact_present"] and man["validation_status"]=="passed","D103 handoff invalid"); expect(man["replayed_decision"]=="d103_sparse_recurrent_microcircuit_scale_confirmed","D103 decision mismatch"); expect(man["replayed_next"]==TASK,"D103 next mismatch"); expect(man["replayed_d104_ready"] is True,"D103 d104_ready mismatch"); expect(man["replayed_final_sparse_candidate"]=="D102_SPARSE_AUTO_ANNEAL_8PCT_LIGHT_PROTECTED_FAIR" and man["replayed_final_sparse_pct"]==8 and man["replayed_final_anneal_pressure"]=="light","D103 sparse candidate mismatch")
    if not man.get("commit_present"): expect(man.get("restore_or_rerun_attempted") and man.get("restore_or_rerun_succeeded"),"missing D103 commit requires restore/rerun")
    expect(dec["decision"]=="d104_sparse_recurrent_generalization_frontier_mapped","unexpected decision"); expect(dec["next"]=="D105_CROSS_FAMILY_TRAIN_LOOP_INTEGRATION_PLAN","unexpected next"); expect(dec["d105_ready"] is True,"d105_ready mismatch")
    expect(dec["final_sparse_pct"]==8 and dec["final_anneal_pressure"]=="light" and dec["final_sparse_candidate_name"]=="D102_SPARSE_AUTO_ANNEAL_8PCT_LIGHT_PROTECTED_FAIR","final sparse identity mismatch")
    expect(dec["failed_jobs"]==[] and dec["fallback_rows"]==0 and dec["scale_reduced"] is False,"failed/fallback/scale issue"); expect(agg["scale"]["scale_reduced"] is False and agg["scale"]["all_required_stress_modes_executed"] and agg["scale"]["all_requested_families_executed"],"scale/family issue"); expect(all(g.values()),f"positive gates failed: {[k for k,v in g.items() if not v]}")
    for r in REPORTS:
        if r in {"d103_upstream_manifest.json","aggregate_metrics.json","decision.json","summary.json","report.md"}: continue
        expect(load(out/r).get("passed") is True,f"{r} not passed")
    expect(m["family_count"]>=14 and m["family_generalization_pass_rate"]>=0.80 and m["heldout_family_pass_rate"]>=0.75 and m["cross_family_transfer_score"]>=0.72 and m["cross_family_rank_stability"]>=0.70,"family generalization threshold failure")
    expect(m["family_fail_count"]>=0 and m["worst_family_name"] and m["worst_family_failure_mode"] and m["no_family_failures_hidden"],"family failure visibility issue")
    expect(m["dense_baseline_preserved"] and m["sparse_candidate_replayed"] and m["sparse_candidate_scale_confirmed"] and m["final_sparse_pct"]==8 and m["final_anneal_pressure"]=="light","sparse identity failure")
    expect(m["protected_components_locked"] and m["protected_component_modification_count"]==0 and m["checkpoint_replay_passed"] and m["checkpoint_replay_match_rate"]>=0.999 and m["sparse_mask_replay_passed"] and m["sparse_mask_replay_match_rate"]>=0.999 and m["sparse_mask_stability_score"]>=0.95 and m["sparse_recovery_rate"]>=0.995,"mask/checkpoint/protected failure")
    for k,t in {"sparse_generalization_test_accuracy":0.9935,"sparse_generalization_ood_accuracy":0.9910,"sparse_generalization_stress_accuracy":0.9905,"sparse_generalization_min_seed_accuracy":0.9900,"sparse_generalization_worst_seed_accuracy":0.9890,"sparse_generalization_convergence_rate":0.9975,"sparse_generalization_loop_usefulness_score":0.69,"sparse_generalization_loop_usefulness_on_tail_score":0.69,"sparse_generalization_state_stability_score":0.79,"sparse_generalization_low_cost_ood_top1_tail_score":0.744,"sparse_generalization_combined_ood_joint_boundary_breakpoint":0.753,"sparse_generalization_inference_cost_reduction_pct":5.8,"sparse_generalization_active_component_reduction_pct":8.0}.items(): expect(m[k]>=t,f"{k} below threshold")
    for k,c in {"sparse_generalization_false_confidence_rate":0.0048,"sparse_generalization_non_convergence_rate":0.0012,"sparse_generalization_oscillation_rate":0.0012,"sparse_generalization_halting_false_positive_rate":0.0048,"sparse_generalization_distance_to_symbolic_teacher":0.028,"sparse_generalization_distance_to_d103_sparse":0.028,"sparse_generalization_distance_to_concrete_oracle_support":0.390,"sparse_generalization_average_support_used":6.78,"memorization_risk_score":0.10}.items(): expect(m[k]<=c,f"{k} above ceiling")
    expect(m["sparse_generalization_routing_failure_rows"]==0 and m["sparse_generalization_D68_preservation_rate"]==1.0 and m["sparse_generalization_top1_guard_preserved"] and not m["sparse_generalization_top1_guard_weakened"],"aggregate guard failure")
    per_ok=sum(1 for f in m["family_results"] if f["family_test_accuracy"]>=0.9935 and f["family_ood_accuracy"]>=0.9910 and f["family_stress_accuracy"]>=0.9905 and f["family_convergence_rate"]>=0.9975 and f["family_loop_usefulness_score"]>=0.69 and f["family_mask_stability_score"]>=0.94)
    expect(per_ok/len(m["family_results"])>=0.80,"per-family pass fraction too low")
    for f in m["family_results"]:
        if f["family_passed_all_hard_gates"]: expect(f["family_routing_failure_rows"]==0 and f["family_D68_preservation_rate"]==1.0 and f["family_top1_guard_preserved"] and not f["family_top1_guard_weakened"] and f["family_rust_path_invoked"] and f["family_fallback_rows"]==0 and f["family_failed_jobs"]==[],f"passing family hard minimum failed: {f['family_name']}")
    expect(m["reference_10_12_15pct_not_used_for_decision"] and m["moderate_aggressive_reference_not_used"] and m["unprotected_pruning_reference_not_used"] and m["protected_component_pruning_sentinel_degraded"] and m["family_label_shortcut_controls_isolated"] and m["control_masks_not_outperforming"] and m["checkpoint_mask_jitter_controls_not_outperforming"] and m["top1_guard_ablation_remains_worse"] and m["partial_corruption_control_remains_worse"] and m["negative_controls_remain_worse"] and m["no_state_and_one_step_controls_remain_worse"],"reference/control failure")
    for key in ["label_shuffle_sentinel_accuracy","regime_label_leak_sentinel_accuracy","family_label_leak_sentinel_accuracy","row_id_lookup_sentinel_accuracy","python_hash_lookup_sentinel_accuracy","file_order_artifact_sentinel_accuracy","seed_id_shortcut_sentinel_accuracy","hidden_state_label_leak_sentinel_accuracy","hidden_state_row_lookup_sentinel_accuracy","hidden_state_family_leak_sentinel_accuracy","halt_step_shortcut_sentinel_accuracy","step_count_shortcut_sentinel_accuracy","mask_id_shortcut_sentinel_accuracy","sparsity_pattern_shortcut_sentinel_accuracy","checkpoint_id_shortcut_sentinel_accuracy","component_id_shortcut_sentinel_accuracy","sparse_mask_replay_shortcut_sentinel_accuracy","sparse_rust_path_shortcut_sentinel_accuracy","family_router_shortcut_sentinel_accuracy"]: expect(m[key]<=0.56,f"{key} shortcut too high")
    expect(not m["forbidden_feature_detected"] and not m["route_distillation_label_leak_risk"] and m["split_integrity_passed"] and not m["train_test_ood_contamination_detected"] and m["sentinel_collapse_passed"],"leak/split/sentinel failure")
    expect(m["deterministic_replay_passed"] and m["report_schema_consistency_passed"] and m["metric_crosscheck_passed"] and m["rust_path_invoked"] and m["fallback_rows"]==0 and m["failed_jobs"]==[],"infrastructure failure"); expect(summ["decision"]==dec["decision"] and summ["next"]==dec["next"],"summary mismatch")
    print(json.dumps({"status":"passed","artifact_path":str(out),"decision":dec["decision"],"next":dec["next"],"family_pass_count":dec["family_pass_count"],"family_fail_count":dec["family_fail_count"]},indent=2,sort_keys=True))
if __name__=="__main__": main()
