#!/usr/bin/env python3
"""Validate D95 combined OOD + joint-boundary scale-confirm artifacts."""
from __future__ import annotations
import argparse, json, sys
from pathlib import Path
REPORTS = ["d94_upstream_manifest.json","d95_scale_confirm_report.json","d94_replay_report.json","combined_ood_joint_boundary_scale_sweep_report.json","joint_required_boundary_scale_sweep_report.json","ood_support_shift_scale_sweep_report.json","combined_low_cost_ood_scale_watch_report.json","combined_low_cost_ood_top1_scale_watch_report.json","low_cost_pressure_scale_watch_report.json","top1_top2_ambiguity_scale_watch_report.json","top1_guard_preservation_scale_report.json","top1_guard_ablation_scale_report.json","top1_guard_partial_corruption_scale_report.json","D68_cheap_top1_regression_guard_scale_report.json","D68_loss_repair_preservation_scale_report.json","hard_correlated_joint_recall_scale_report.json","hard_adversarial_joint_recall_scale_report.json","external_required_scale_watch_report.json","indistinguishable_abstain_scale_watch_report.json","safety_margin_scale_watch_report.json","oracle_distance_frontier_scale_report.json","support_cost_frontier_scale_report.json","truth_leak_audit_scale_report.json","rust_invocation_scale_report.json","aggregate_metrics.json","decision.json","summary.json","report.md"]
ALLOWED = {"combined_ood_joint_boundary_scale_confirmed","combined_ood_joint_boundary_scale_tail_risk","combined_ood_joint_boundary_scale_safety_regression","top1_guard_invariant_violation","combined_ood_joint_boundary_scale_not_confirmed"}
def load(p:Path): return json.loads(p.read_text(encoding="utf-8"))
def fail(m): print(f"D95 check failed: {m}", file=sys.stderr); sys.exit(1)
def main():
    p=argparse.ArgumentParser(); p.add_argument("--out",default="target/pilot_wave/d95_combined_ood_joint_boundary_scale_confirm"); args=p.parse_args(); out=Path(args.out)
    missing=[r for r in REPORTS if not (out/r).exists()]
    if missing: fail(f"missing reports {missing}")
    man=load(out/"d94_upstream_manifest.json"); agg=load(out/"aggregate_metrics.json"); dec=load(out/"decision.json"); scale=load(out/"d95_scale_confirm_report.json"); replay=load(out/"d94_replay_report.json"); combo=load(out/"combined_ood_joint_boundary_scale_sweep_report.json"); joint=load(out/"joint_required_boundary_scale_sweep_report.json"); ood=load(out/"ood_support_shift_scale_sweep_report.json"); co=load(out/"combined_low_cost_ood_scale_watch_report.json"); ctop=load(out/"combined_low_cost_ood_top1_scale_watch_report.json"); low=load(out/"low_cost_pressure_scale_watch_report.json"); topamb=load(out/"top1_top2_ambiguity_scale_watch_report.json"); preserve=load(out/"top1_guard_preservation_scale_report.json"); ab=load(out/"top1_guard_ablation_scale_report.json"); partial=load(out/"top1_guard_partial_corruption_scale_report.json"); cheap=load(out/"D68_cheap_top1_regression_guard_scale_report.json"); d68=load(out/"D68_loss_repair_preservation_scale_report.json"); corr=load(out/"hard_correlated_joint_recall_scale_report.json"); adv=load(out/"hard_adversarial_joint_recall_scale_report.json"); ext=load(out/"external_required_scale_watch_report.json"); abst=load(out/"indistinguishable_abstain_scale_watch_report.json"); safety=load(out/"safety_margin_scale_watch_report.json"); oracle=load(out/"oracle_distance_frontier_scale_report.json"); support=load(out/"support_cost_frontier_scale_report.json"); truth=load(out/"truth_leak_audit_scale_report.json"); rust=load(out/"rust_invocation_scale_report.json")
    if dec.get("decision") not in ALLOWED: fail(f"bad decision {dec.get('decision')}")
    if dec.get("decision") != "combined_ood_joint_boundary_scale_confirmed": fail(f"unexpected decision {dec.get('decision')}")
    if dec.get("next") != "D96_NEXT_BREAKPOINT_OR_GENERALIZATION_PLAN": fail(f"unexpected next {dec.get('next')}")
    if agg.get("failed_jobs") or dec.get("failed_jobs") or rust.get("failed_jobs"): fail("failed_jobs present")
    if agg.get("fallback_rows") != 0 or rust.get("fallback_rows") != 0: fail("fallback_rows nonzero")
    d94=man.get("d94_artifacts",{})
    if man.get("requested_d94_commit") != "2f440dccf572864304114d5e6b5d0f1284b4b0d0": fail("requested D94 commit mismatch")
    restore=man.get("restore",{})
    if not man.get("commit_present") and not (man.get("restore_or_rerun_attempted") and man.get("restore_or_rerun_succeeded")): fail("D94 commit missing without successful restore/rerun")
    if not man.get("artifact_present"): fail("D94 artifact missing")
    if man.get("validation_status") != "passed": fail(f"D94 validation status {man.get('validation_status')}")
    if d94.get("decision") != "combined_ood_joint_boundary_repair_confirmed": fail(f"D94 decision mismatch {d94.get('decision')}")
    if d94.get("next") != "D95_COMBINED_OOD_JOINT_BOUNDARY_SCALE_CONFIRM": fail(f"D94 next mismatch {d94.get('next')}")
    if d94.get("best_arm") != "COMBINED_OOD_JOINT_BOUNDARY_REPAIR_COST_AWARE": fail(f"D94 best mismatch {d94.get('best_arm')}")
    if d94.get("top1_guard_weakened") is True: fail("D94 top1 guard weakened")
    best=agg.get("best_fair_arm",{})
    if best.get("arm") != "COMBINED_OOD_JOINT_BOUNDARY_REPAIR_COST_AWARE_SCALE": fail(f"unexpected best {best.get('arm')}")
    gates={"combined_ood_joint_boundary_breakpoint":best.get("combined_ood_joint_boundary_breakpoint",0)>=0.755,"min_seed_combined_ood_joint_boundary_breakpoint":best.get("min_seed_combined_ood_joint_boundary_breakpoint",0)>=0.752,"combined_low_cost_plus_ood_breakpoint":best.get("combined_low_cost_plus_ood_breakpoint",0)>=0.760,"ood_support_distribution_shift_breakpoint":best.get("ood_support_distribution_shift_breakpoint",0)>=0.760,"joint_required_near_boundary_breakpoint":best.get("joint_required_near_boundary_breakpoint",0)>=0.779,"combined_low_cost_ood_top1_ambiguity_breakpoint":best.get("combined_low_cost_ood_top1_ambiguity_breakpoint",0)>=0.741,"exact_joint_accuracy":best.get("exact_joint_accuracy",0)>=0.9990,"correlated_echo_accuracy":best.get("correlated_echo_accuracy",0)>=0.995,"adversarial_distractor_accuracy":best.get("adversarial_distractor_accuracy",0)>=0.995,"external_test_required_accuracy":best.get("external_test_required_accuracy",0)>=0.995,"min_seed_exact_joint_accuracy":best.get("min_seed_exact_joint_accuracy",0)>=0.9988,"min_seed_correlated_echo_accuracy":best.get("min_seed_correlated_echo_accuracy",0)>=0.9945,"min_seed_adversarial_distractor_accuracy":best.get("min_seed_adversarial_distractor_accuracy",0)>=0.9945,"min_seed_external_test_required_accuracy":best.get("min_seed_external_test_required_accuracy",0)>=0.9945,"false_confidence_rate":best.get("false_confidence_rate",1)<=0.0044,"indistinguishable_abstain_rate":best.get("indistinguishable_abstain_rate",0)>=0.9948,"average_total_support_used":best.get("average_total_support_used",99)<=6.72,"distance_to_concrete_oracle_support":best.get("distance_to_concrete_oracle_support",99)<=0.38,"joint_counter_recall_on_joint_required_rows":best.get("joint_counter_recall_on_joint_required_rows",0)>=0.9940,"external_recall_on_external_required_rows":best.get("external_recall_on_external_required_rows",0)>=0.9957,"wrong_concrete_counter_rate":best.get("wrong_concrete_counter_rate",1)<=0.0007,"weak_top1_top2_path_failure_rate":best.get("weak_top1_top2_path_failure_rate",1)<=0.0006,"top1_top2_sufficient_false_joint_rate":best.get("top1_top2_sufficient_false_joint_rate",1)<=0.0015,"D68_loss_repair_preservation_rate":best.get("D68_loss_repair_preservation_rate")==1.0,"routing_failure_rows":best.get("routing_failure_rows")==0,"top1_guard_preserved":best.get("top1_guard_preserved") is True and preserve.get("top1_guard_preserved") is True,"top1_guard_weakened":best.get("top1_guard_weakened") is False and preserve.get("top1_guard_weakened") is False,"top1_guard_ablation_remains_worse":ab.get("guard_ablation_worse") is True,"partial_corruption_control_remains_worse":partial.get("partial_corruption_worse") is True,"truth_leak_audit_passed":truth.get("passed") is True,"rust_path_invoked":best.get("rust_path_invoked") is True,"fallback_rows":best.get("fallback_rows")==0,"failed_jobs":best.get("failed_jobs")==[]}
    failed=[k for k,v in gates.items() if not v]
    if failed: fail(f"positive gates failed {failed}")
    for name,rep in [("scale",scale),("replay",replay),("combo",combo),("joint",joint),("ood",ood),("combined_low_cost_ood",co),("combined_top1",ctop),("low",low),("topamb",topamb),("preserve",preserve),("ablation",ab),("partial",partial),("cheap",cheap),("d68",d68),("corr",corr),("adv",adv),("external",ext),("abstain",abst),("safety",safety),("oracle",oracle),("support",support),("truth",truth),("rust",rust)]:
        if not rep.get("passed"): fail(f"{name} report failed")
    if truth.get("fair_arms_using_truth_label") or truth.get("fair_arms_using_support_regime_label") or truth.get("label_echo_fair_oracle_used") or truth.get("row_id_lookup_used") or truth.get("python_hash_used") or not truth.get("oracle_arms_reference_only"): fail("truth leak hard gate failed")
    print(json.dumps({"check":"passed","out":str(out),"decision":dec,"best_fair_arm":best.get("arm"),"combined_ood_joint_boundary_breakpoint":best.get("combined_ood_joint_boundary_breakpoint"),"min_seed_combined_ood_joint_boundary_breakpoint":best.get("min_seed_combined_ood_joint_boundary_breakpoint"),"failed_jobs":agg.get("failed_jobs")}, indent=2))
if __name__ == "__main__": main()
