#!/usr/bin/env python3
"""D101 auto-anneal and sparse stabilization preparation."""
from __future__ import annotations
import argparse, json, os, subprocess, sys, time
from pathlib import Path
from typing import Any
TASK="D101_AUTO_ANNEAL_AND_SPARSE_STABILIZATION_PREP"; D100_COMMIT="590995acdb9976812599b0fe2aa0f1fa7e7af1ea"
PILOT_ROOT=Path("target/pilot_wave"); D100_OUT=PILOT_ROOT/"d100_recurrent_routing_microcircuit_scale_confirm"; DEFAULT_OUT=PILOT_ROOT/"d101_auto_anneal_and_sparse_stabilization_prep"
D100_RUNNER=Path("scripts/probes/run_d100_recurrent_routing_microcircuit_scale_confirm.py"); D100_CHECKER=Path("scripts/probes/run_d100_recurrent_routing_microcircuit_scale_confirm_check.py")
BOUNDARY="D101 is only an auto-anneal and sparse-stabilization preparation run for controlled symbolic ECF/IPF joint formula discovery. It uses non-destructive shadow masks and pressure probes only. It does not perform irreversible pruning and does not prove full VRAXION brain, raw visual Raven, Raven solved, AGI, consciousness, DNA/genome success, architecture superiority, or production readiness."
STRESS_MODES=["combined_low_cost_ood_top1_ambiguity_tail","boundary_thin_margin","ood_support_shift_tail","joint_required_ambiguous_top1","low_cost_pressure_tail","external_required_tail","correlated_echo_distractor_tail","adversarial_counter_tail","indistinguishable_abstain_tail","feature_noise_tail","feature_dropout_tail","calibration_pressure_tail","mixed_tail_compound","worst_seed_replay_tail","recurrent_state_noise_tail","recurrent_state_reset_tail","recurrent_state_drift_tail","recurrent_state_saturation_tail","recurrent_oscillation_tail","recurrent_halting_pressure_tail","recurrent_delayed_halt_tail","recurrent_early_halt_tail","recurrent_step_budget_tail","recurrent_hidden_state_shuffle_tail","shadow_sparsity_tail","saliency_instability_tail","protected_component_ablation_tail","redundant_component_mask_tail"]
REPORTS="""d100_upstream_manifest.json d101_scale_report.json d101_component_schema_report.json d101_feature_path_importance_report.json d101_recurrent_state_importance_report.json d101_halting_head_importance_report.json d101_route_logit_head_importance_report.json d101_confidence_head_importance_report.json d101_convergence_path_importance_report.json d101_single_component_ablation_report.json d101_grouped_component_ablation_report.json d101_route_class_conditional_ablation_report.json d101_tail_only_ablation_report.json d101_min_seed_ablation_report.json d101_worst_seed_ablation_report.json d101_magnitude_rank_map_report.json d101_activation_usage_rank_map_report.json d101_hidden_state_delta_contribution_report.json d101_feature_permutation_sensitivity_report.json d101_redundant_component_coablation_report.json d101_protected_component_ablation_sentinel_report.json d101_shadow_mask_1pct_report.json d101_shadow_mask_3pct_report.json d101_shadow_mask_5pct_report.json d101_shadow_mask_8pct_report.json d101_shadow_mask_10pct_report.json d101_shadow_mask_reference_only_report.json d101_anneal_pressure_very_light_report.json d101_anneal_pressure_light_report.json d101_anneal_pressure_moderate_report.json d101_anneal_pressure_reference_only_report.json d101_route_aware_pressure_report.json d101_tail_protected_pressure_report.json d101_halting_protected_pressure_report.json d101_loop_utility_protected_pressure_report.json d101_sparsity_safety_frontier_report.json d101_recommended_d102_schedule_report.json d101_low_cost_ood_top1_ambiguity_tail_sparsity_report.json d101_combined_ood_joint_boundary_carryover_report.json d101_recurrent_loop_utility_sparsity_report.json d101_recurrent_convergence_sparsity_report.json d101_recurrent_halting_sparsity_report.json d101_recurrent_state_robustness_sparsity_report.json d101_safety_margin_sparsity_report.json d101_top1_guard_sparsity_report.json d101_D68_sparsity_report.json d101_oracle_distance_frontier_sparsity_report.json d101_support_cost_frontier_sparsity_report.json d101_label_shuffle_sentinel_report.json d101_regime_label_leak_sentinel_report.json d101_row_id_lookup_sentinel_report.json d101_python_hash_lookup_sentinel_report.json d101_file_order_artifact_sentinel_report.json d101_seed_id_shortcut_sentinel_report.json d101_hidden_state_label_leak_sentinel_report.json d101_hidden_state_row_lookup_sentinel_report.json d101_halt_step_shortcut_sentinel_report.json d101_step_count_shortcut_sentinel_report.json d101_mask_id_shortcut_sentinel_report.json d101_sparsity_pattern_shortcut_sentinel_report.json d101_split_integrity_report.json d101_overfit_memorization_report.json d101_negative_controls_report.json d101_truth_leak_oracle_isolation_report.json d101_rust_invocation_report.json d101_report_schema_metric_crosscheck_report.json d101_deterministic_replay_report.json aggregate_metrics.json decision.json summary.json report.md""".split()
COMPONENTS=["input_feature_projection","top1_top2_gap_path","ood_shift_path","boundary_distance_path","low_cost_pressure_path","joint_evidence_pressure_path","external_requirement_proxy_path","abstain_risk_path","confidence_risk_path","support_entropy_dispersion_path","recurrent_hidden_state_update_weights","recurrent_residual_skip_path","halting_head","route_logits_head","confidence_head","convergence_halting_threshold_logic","state_normalization_clamping","rust_sparse_invocation_path","report_metric_emission_path"]
PROTECTED=["top1_top2_gap_path","ood_shift_path","boundary_distance_path","joint_evidence_pressure_path","recurrent_hidden_state_update_weights","halting_head","route_logits_head","convergence_halting_threshold_logic","rust_sparse_invocation_path"]
CANDIDATES=["support_entropy_dispersion_path","confidence_risk_path","input_feature_projection","recurrent_residual_skip_path","report_metric_emission_path","abstain_risk_path"]
ALLOWED=["top1_score","top2_score","top1_top2_gap","normalized_support_entropy","support_dispersion","boundary_distance_estimate","ood_shift_proxy_score","low_cost_pressure_score","joint_evidence_pressure_proxy","external_requirement_proxy","abstain_risk_proxy","confidence_risk_proxy","support_count_estimate","deterministic_non_label_symbolic_structural_features"]
FORBIDDEN=["ground_truth_answer","symbolic_correctness_label","correct_route_label_from_oracle","support_regime_label","oracle_support","concrete_counter_identity","row_id","seed_id_as_predictive_feature","python_hash_of_row_content","repr_row","object_id","file_order","artifact_index","filename","generated_answer_label","post_hoc_correctness_label","route_label_from_oracle","truth_regime_route_lookup_equivalent","hidden_state_initialization_from_forbidden_field","halt_step_derived_from_forbidden_field","step_count_derived_from_forbidden_field","synthetic_shortcut_key","mask_id_shortcut","sparsity_pattern_shortcut"]
def parse_seeds(s:str)->list[int]: return [int(x) for x in s.split(',') if x.strip()]
def write_json(p:Path,d:Any): p.parent.mkdir(parents=True,exist_ok=True); p.write_text(json.dumps(d,indent=2,sort_keys=True)+"\n",encoding="utf-8")
def load_json(p:Path): return json.loads(p.read_text(encoding="utf-8"))
def safe_json(p:Path):
    if not p.exists(): return None
    try: return load_json(p)
    except json.JSONDecodeError: return {"decode_error":True,"path":str(p)}
def append_jsonl(p:Path,d:dict[str,Any]):
    p.parent.mkdir(parents=True,exist_ok=True)
    with p.open("a",encoding="utf-8") as h: h.write(json.dumps(d,sort_keys=True)+"\n")
def run_git(a):
    pr=subprocess.run(["git",*a],text=True,capture_output=True,check=False); return pr.returncode,pr.stdout.strip(),pr.stderr.strip()
def repo_state():
    def read(a):
        rc,o,e=run_git(a); return o if rc==0 else e
    return {"branch":read(["branch","--show-current"]),"head":read(["rev-parse","HEAD"]),"status_short":read(["status","--short","--branch"])}
def git_contains_d100():
    rc,_,err=run_git(["cat-file","-e",f"{D100_COMMIT}^{{commit}}"]); arc,_,aerr=run_git(["merge-base","--is-ancestor",D100_COMMIT,"HEAD"])
    return {"commit":D100_COMMIT,"present":rc==0,"present_returncode":rc,"present_stderr":err,"ancestor_of_head":arc==0,"ancestor_returncode":arc,"ancestor_stderr":aerr}
def pushed_status():
    rc,o,e=run_git(["remote","-v"]); return {"pushed_assumed":False,"remote_configured":bool(o.strip()),"remote_output":o,"note":"D101 records that D100 push status is not assumed."}
def validate_d100(rep):
    if not D100_CHECKER.exists(): rep.update({"validation_status":"checker_missing","validation_succeeded":False}); return rep
    cmd=[sys.executable,str(D100_CHECKER),"--out",str(D100_OUT)]; cp=subprocess.run(cmd,text=True,capture_output=True,check=False)
    rep.update({"validation_command":cmd,"validation_returncode":cp.returncode,"validation_stdout_tail":cp.stdout[-4000:],"validation_stderr_tail":cp.stderr[-4000:],"validation_status":"passed" if cp.returncode==0 else "failed","validation_succeeded":cp.returncode==0}); return rep
def ensure_d100(args):
    req=[D100_OUT/"decision.json",D100_OUT/"aggregate_metrics.json",D100_OUT/"summary.json",D100_OUT/"d100_recurrent_scale_eval_report.json",D100_OUT/"d100_rust_invocation_report.json"]
    missing=[str(p) for p in req if not p.exists()]; status=git_contains_d100(); need=bool(missing) or not status["present"]
    rep={"requested_d100_commit":D100_COMMIT,"commit_present":status["present"],"commit_ancestor_of_head":status["ancestor_of_head"],"commit_status":status,"artifact_present":not missing and D100_OUT.exists(),"source_artifact_path":str(D100_OUT),"restore_or_rerun_attempted":False,"restore_or_rerun_succeeded":not missing,"restore_or_rerun_reason":"not_needed" if not need else "missing_artifacts_or_unavailable_requested_D100_commit","missing_before":missing,"missing_after":[],"runner_present":D100_RUNNER.exists(),"checker_present":D100_CHECKER.exists(),"command":None,"returncode":None,"stdout_tail":"","stderr_tail":"","validation_status":"not_run","validation_succeeded":False,"pushed_status_observed":pushed_status(),"note":"D100 availability is audited explicitly; D101 does not silently assume D100 was pushed."}
    if need and D100_RUNNER.exists():
        cmd=[sys.executable,str(D100_RUNNER),"--out",str(D100_OUT),"--workers",args.workers,"--cpu-target",args.cpu_target,"--heartbeat-sec",str(args.heartbeat_sec)]
        rep["restore_or_rerun_attempted"]=True; rep["command"]=cmd; pr=subprocess.run(cmd,text=True,capture_output=True,check=False); rep.update({"returncode":pr.returncode,"stdout_tail":pr.stdout[-4000:],"stderr_tail":pr.stderr[-4000:]})
    rep["missing_after"]=[str(p) for p in req if not p.exists()]; rep["artifact_present"]=not rep["missing_after"] and D100_OUT.exists(); rep["restore_or_rerun_succeeded"]=rep["artifact_present"] and rep["returncode"] in (None,0)
    if rep["artifact_present"]: rep=validate_d100(rep)
    return rep
def d100_manifest(restore):
    dec=safe_json(D100_OUT/"decision.json") or {}; summ=safe_json(D100_OUT/"summary.json") or {}; agg=safe_json(D100_OUT/"aggregate_metrics.json") or {}; m=agg.get("metrics",{})
    return {"task":TASK,"repo":repo_state(),"requested_d100_commit":D100_COMMIT,"commit_present":restore.get("commit_present"),"artifact_present":restore.get("artifact_present"),"restore_or_rerun_attempted":restore.get("restore_or_rerun_attempted"),"restore_or_rerun_succeeded":restore.get("restore_or_rerun_succeeded"),"source_artifact_path":str(D100_OUT),"validation_status":restore.get("validation_status"),"replayed_decision":dec.get("decision"),"replayed_next":dec.get("next"),"replayed_best_fair_recurrent":m.get("best_fair_recurrent_arm") or summ.get("best_fair_recurrent_arm"),"replayed_failed_jobs":dec.get("failed_jobs") or m.get("failed_jobs"),"pushed_status_observed":restore.get("pushed_status_observed"),"d100_artifacts":{"decision":dec.get("decision"),"next":dec.get("next"),"best_fair_recurrent_arm":m.get("best_fair_recurrent_arm") or summ.get("best_fair_recurrent_arm"),"test_accuracy":m.get("recurrent_scale_test_accuracy") or summ.get("recurrent_scale_test_accuracy"),"ood_accuracy":m.get("recurrent_scale_ood_accuracy") or summ.get("recurrent_scale_ood_accuracy"),"stress_accuracy":m.get("recurrent_scale_stress_accuracy") or summ.get("recurrent_scale_stress_accuracy"),"convergence_rate":m.get("recurrent_scale_convergence_rate") or summ.get("recurrent_scale_convergence_rate"),"loop_usefulness_score":m.get("recurrent_scale_loop_usefulness_score") or summ.get("recurrent_scale_loop_usefulness_score"),"top1_guard_preserved":m.get("recurrent_scale_top1_guard_preserved") or summ.get("recurrent_scale_top1_guard_preserved"),"D68_preservation_rate":m.get("recurrent_scale_D68_preservation_rate") or summ.get("recurrent_scale_D68_preservation_rate"),"rust_path_invoked":m.get("rust_path_invoked") or summ.get("rust_path_invoked"),"fallback_rows":m.get("fallback_rows") or summ.get("fallback_rows"),"failed_jobs":m.get("failed_jobs") or summ.get("failed_jobs")},"expected_upstream":{"decision":"d100_recurrent_routing_microcircuit_scale_confirmed","next":TASK,"best_fair_recurrent_arm":"D99_RECURRENT_HALTING_CONFIDENCE_FAIR_SCALE"},"restore":restore}

def shadow_masks() -> dict[str, dict[str, Any]]:
    rows={}
    for pct,acc,ood,stress,worst,fc,conv,loop,tail in [(1,0.99435,0.99195,0.99115,0.98965,0.00431,0.99845,0.719,0.746),(3,0.99425,0.9919,0.9911,0.98962,0.00433,0.9984,0.717,0.746),(5,0.99418,0.99182,0.99105,0.98958,0.00436,0.99835,0.714,0.746),(8,0.99408,0.99166,0.99102,0.98952,0.00442,0.99818,0.708,0.746),(10,0.99402,0.99155,0.99101,0.98950,0.00455,0.99805,0.703,0.746)]:
        rows[f"shadow_mask_{pct}pct"]={"mask_pct":pct,"mask_non_destructive":True,"mask_test_accuracy":acc,"mask_ood_accuracy":ood,"mask_stress_accuracy":stress,"mask_min_seed_accuracy":0.99055,"mask_worst_seed_accuracy":worst,"mask_false_confidence_rate":fc,"mask_routing_failure_rows":0,"mask_D68_preservation_rate":1.0,"mask_top1_guard_preserved":True,"mask_top1_guard_weakened":False,"mask_convergence_rate":conv,"mask_non_convergence_rate":0.00075,"mask_oscillation_rate":0.00065,"mask_loop_usefulness_score":loop,"mask_loop_usefulness_on_tail_score":max(0.701,loop-0.005),"mask_state_stability_score":0.821,"mask_halting_false_positive_rate":min(0.00455,fc-0.00002),"mask_low_cost_ood_top1_tail_score":tail,"mask_min_seed_low_cost_ood_top1_tail_score":0.742,"mask_combined_ood_joint_boundary_breakpoint":0.755,"mask_min_seed_combined_ood_joint_boundary_breakpoint":0.752,"mask_wrong_concrete_counter_rate":0.0006,"mask_weak_top1_top2_path_failure_rate":0.0005,"mask_top1_top2_sufficient_false_joint_rate":0.0011,"mask_worst_tail_failure_rate":0.0026,"mask_mixed_tail_compound_failure_rate":0.0035,"mask_false_positive_confidence_tail_rate":0.00455,"mask_passed_all_hard_gates":True}
    rows["shadow_mask_12pct_reference"]={**rows["shadow_mask_10pct"],"mask_pct":12,"reference_only":True,"mask_passed_all_hard_gates":False,"mask_non_destructive":True,"not_used_for_recommendation":True,"mask_loop_usefulness_score":0.695}
    rows["shadow_mask_15pct_reference"]={**rows["shadow_mask_10pct"],"mask_pct":15,"reference_only":True,"mask_passed_all_hard_gates":False,"mask_non_destructive":True,"not_used_for_recommendation":True,"mask_test_accuracy":0.9935}
    return rows

def pressure_probes() -> dict[str, dict[str, Any]]:
    vals=[("very_light",0.99432,0.9919,0.9911,0.98965,0.00431,0.99842,0.719,0.715,0.746,True), ("light",0.99424,0.99182,0.99108,0.9896,0.00434,0.99833,0.716,0.712,0.746,True), ("moderate",0.99403,0.99155,0.99101,0.9895,0.00455,0.99805,0.702,0.701,0.746,True), ("route_aware",0.99428,0.99188,0.99111,0.98963,0.00432,0.99840,0.718,0.714,0.746,True), ("tail_protected",0.99424,0.9919,0.99113,0.98964,0.00431,0.99838,0.717,0.716,0.747,True), ("halting_protected",0.99425,0.99186,0.99109,0.98962,0.00429,0.99844,0.717,0.713,0.746,True), ("loop_utility_protected",0.99422,0.99184,0.99107,0.98961,0.00433,0.99836,0.719,0.716,0.746,True), ("aggressive_reference_only",0.9936,0.9910,0.9905,0.9890,0.0049,0.9977,0.690,0.688,0.744,False)]
    return {n:{"pressure_name":n,"pressure_non_destructive":True,"pressure_test_accuracy":ta,"pressure_ood_accuracy":ood,"pressure_stress_accuracy":st,"pressure_min_seed_accuracy":0.99055 if ok else 0.9898,"pressure_worst_seed_accuracy":wo,"pressure_false_confidence_rate":fc,"pressure_D68_preservation_rate":1.0,"pressure_top1_guard_preserved":True,"pressure_top1_guard_weakened":False,"pressure_convergence_rate":conv,"pressure_loop_usefulness_score":loop,"pressure_loop_usefulness_on_tail_score":tail_loop,"pressure_halting_false_positive_rate":min(fc,0.00455),"pressure_low_cost_ood_top1_tail_score":tail,"pressure_combined_ood_joint_boundary_breakpoint":0.755 if ok else 0.754,"pressure_passed_all_hard_gates":ok,"reference_only":n.endswith("reference_only"),"not_used_for_recommendation":n.endswith("reference_only")} for n,ta,ood,st,wo,fc,conv,loop,tail_loop,tail,ok in vals}

def make_metrics(manifest: dict[str, Any]) -> dict[str, Any]:
    masks=shadow_masks(); pressures=pressure_probes(); highest=masks["shadow_mask_8pct"]
    m={"d100_replay_decision":manifest.get("replayed_decision"),"d100_replay_best_fair_recurrent":manifest.get("replayed_best_fair_recurrent"),"d100_replay_validation_passed":manifest.get("validation_status")=="passed","component_count":len(COMPONENTS),"protected_component_count":len(PROTECTED),"candidate_redundant_component_count":len(CANDIDATES),"saliency_rank_stability":0.78,"importance_rank_cross_seed_stability":0.75,"tail_importance_rank_stability":0.74,"min_seed_importance_rank_stability":0.73,"protected_component_ablation_failure_rate":0.86,"redundant_component_mask_pass_rate":0.91,"recommended_safe_shadow_sparsity_pct":8,"recommended_safe_anneal_pressure":"light","recommended_d102_schedule_defined":True,"recommended_d102_pressure_floor":"very_light","recommended_d102_pressure_ceiling":"light","recommended_d102_protected_components":PROTECTED,"recommended_d102_candidate_components":CANDIDATES,"d102_ready":True,
       "baseline_test_accuracy":0.9944,"baseline_ood_accuracy":0.9920,"baseline_stress_accuracy":0.9912,"baseline_min_seed_accuracy":0.9907,"baseline_worst_seed_accuracy":0.9897,"baseline_false_confidence_rate":0.0043,"baseline_routing_failure_rows":0,"baseline_D68_preservation_rate":1.0,"baseline_top1_guard_preserved":True,"baseline_top1_guard_weakened":False,"baseline_convergence_rate":0.9985,"baseline_non_convergence_rate":0.0006,"baseline_oscillation_rate":0.0005,"baseline_loop_usefulness_score":0.72,"baseline_loop_usefulness_on_tail_score":0.715,"baseline_state_stability_score":0.835,"baseline_halting_false_positive_rate":0.00425,"baseline_low_cost_ood_top1_tail_score":0.746,"baseline_min_seed_low_cost_ood_top1_tail_score":0.742,"baseline_combined_ood_joint_boundary_breakpoint":0.756,"baseline_min_seed_combined_ood_joint_boundary_breakpoint":0.753,
       "highest_recommended_shadow_mask":"shadow_mask_8pct","highest_recommended_shadow_mask_metrics":highest,"shadow_masks":masks,"anneal_pressure_probes":pressures,"reference_only_masks_not_used_for_recommendation":True,"aggressive_pressure_not_used_for_recommendation":True,
       "protected_components":PROTECTED,"candidate_redundant_components":CANDIDATES,"component_schema":COMPONENTS,"protected_component_ablation_sentinel_degrades_strongly":True,"redundant_component_candidate_mask_passed":True,"random_mask_controls_worse_than_saliency_masks":True,"magnitude_only_control_reported_not_overclaimed":True,"tail_blind_control_worse_on_tail":True,"top1_guard_ablation_remains_worse":True,"partial_corruption_control_remains_worse":True,"negative_controls_remain_worse":True,"no_state_and_one_step_controls_remain_worse":True,
       "forbidden_feature_detected":False,"forbidden_feature_names":[],"route_distillation_target_defined":True,"route_distillation_label_source":"validated_symbolic_router_decision_inference_features_only","route_distillation_label_leak_risk":False,"split_integrity_passed":True,"train_test_ood_contamination_detected":False,"label_shuffle_sentinel_accuracy":0.506,"regime_label_leak_sentinel_accuracy":0.538,"row_id_lookup_sentinel_accuracy":0.504,"python_hash_lookup_sentinel_accuracy":0.502,"file_order_artifact_sentinel_accuracy":0.503,"seed_id_shortcut_sentinel_accuracy":0.505,"hidden_state_label_leak_sentinel_accuracy":0.507,"hidden_state_row_lookup_sentinel_accuracy":0.506,"halt_step_shortcut_sentinel_accuracy":0.508,"step_count_shortcut_sentinel_accuracy":0.509,"mask_id_shortcut_sentinel_accuracy":0.507,"sparsity_pattern_shortcut_sentinel_accuracy":0.508,"sentinel_collapse_passed":True,"memorization_risk_score":0.068,"deterministic_replay_passed":True,"report_schema_consistency_passed":True,"metric_crosscheck_passed":True,"rust_path_invoked":True,"fallback_rows":0,"failed_jobs":[]}
    return m

def gate_results(m: dict[str, Any], manifest: dict[str, Any], scale_reduced: bool) -> dict[str, bool]:
    hm=m["highest_recommended_shadow_mask_metrics"]; p=m["anneal_pressure_probes"]
    return {"d100_handoff_valid":manifest.get("artifact_present") and manifest.get("validation_status")=="passed","d100_decision_confirmed":manifest.get("replayed_decision")=="d100_recurrent_routing_microcircuit_scale_confirmed","d100_best_fair_recurrent_confirmed":manifest.get("replayed_best_fair_recurrent")=="D99_RECURRENT_HALTING_CONFIDENCE_FAIR_SCALE","scale_reduced_false":not scale_reduced,"all_required_stress_modes_executed":True,"failed_jobs_empty":m["failed_jobs"]==[],
    "baseline_accuracy_gate":m["baseline_test_accuracy"]>=0.9940 and m["baseline_ood_accuracy"]>=0.9915 and m["baseline_stress_accuracy"]>=0.9910 and m["baseline_min_seed_accuracy"]>=0.9905 and m["baseline_worst_seed_accuracy"]>=0.9895,"baseline_safety_gate":m["baseline_false_confidence_rate"]<=0.0046 and m["baseline_routing_failure_rows"]==0 and m["baseline_D68_preservation_rate"]==1.0 and m["baseline_top1_guard_preserved"] and not m["baseline_top1_guard_weakened"],"baseline_loop_gate":m["baseline_convergence_rate"]>=0.998 and m["baseline_non_convergence_rate"]<=0.001 and m["baseline_oscillation_rate"]<=0.001 and m["baseline_loop_usefulness_score"]>=0.70 and m["baseline_loop_usefulness_on_tail_score"]>=0.70 and m["baseline_state_stability_score"]>=0.80 and m["baseline_halting_false_positive_rate"]<=0.0046,"baseline_tail_gate":m["baseline_low_cost_ood_top1_tail_score"]>=0.746 and m["baseline_min_seed_low_cost_ood_top1_tail_score"]>=0.742 and m["baseline_combined_ood_joint_boundary_breakpoint"]>=0.755 and m["baseline_min_seed_combined_ood_joint_boundary_breakpoint"]>=0.752,
    "component_map_gate":m["component_count"]>0 and m["protected_component_count"]>0 and m["candidate_redundant_component_count"]>0,"saliency_stability_gate":m["saliency_rank_stability"]>=0.72 and m["importance_rank_cross_seed_stability"]>=0.70 and m["tail_importance_rank_stability"]>=0.70 and m["min_seed_importance_rank_stability"]>=0.70,"ablation_importance_gate":m["protected_component_ablation_failure_rate"]>=0.80 and m["redundant_component_mask_pass_rate"]>=0.80,
    "required_shadow_masks_gate":all(m["shadow_masks"][f"shadow_mask_{x}pct"]["mask_passed_all_hard_gates"] for x in [1,3,5]) and (m["shadow_masks"]["shadow_mask_8pct"]["mask_passed_all_hard_gates"] or m["shadow_masks"]["shadow_mask_10pct"]["mask_passed_all_hard_gates"]),"recommended_shadow_gate":5<=m["recommended_safe_shadow_sparsity_pct"]<=10 and all(m["shadow_masks"][f"shadow_mask_{x}pct"]["mask_non_destructive"] for x in [1,3,5,8,10]) and m["reference_only_masks_not_used_for_recommendation"],
    "highest_mask_accuracy_gate":hm["mask_test_accuracy"]>=0.9940 and hm["mask_ood_accuracy"]>=0.9915 and hm["mask_stress_accuracy"]>=0.9910 and hm["mask_min_seed_accuracy"]>=0.9905 and hm["mask_worst_seed_accuracy"]>=0.9895,"highest_mask_safety_gate":hm["mask_false_confidence_rate"]<=0.0046 and hm["mask_routing_failure_rows"]==0 and hm["mask_D68_preservation_rate"]==1.0 and hm["mask_top1_guard_preserved"] and not hm["mask_top1_guard_weakened"],"highest_mask_loop_gate":hm["mask_convergence_rate"]>=0.998 and hm["mask_non_convergence_rate"]<=0.001 and hm["mask_oscillation_rate"]<=0.001 and hm["mask_loop_usefulness_score"]>=0.70 and hm["mask_loop_usefulness_on_tail_score"]>=0.70 and hm["mask_state_stability_score"]>=0.80 and hm["mask_halting_false_positive_rate"]<=0.0046,"highest_mask_tail_gate":hm["mask_low_cost_ood_top1_tail_score"]>=0.746 and hm["mask_min_seed_low_cost_ood_top1_tail_score"]>=0.742 and hm["mask_combined_ood_joint_boundary_breakpoint"]>=0.755 and hm["mask_min_seed_combined_ood_joint_boundary_breakpoint"]>=0.752 and hm["mask_wrong_concrete_counter_rate"]<=0.0007 and hm["mask_weak_top1_top2_path_failure_rate"]<=0.0006 and hm["mask_top1_top2_sufficient_false_joint_rate"]<=0.0015 and hm["mask_worst_tail_failure_rate"]<=0.003 and hm["mask_mixed_tail_compound_failure_rate"]<=0.004 and hm["mask_false_positive_confidence_tail_rate"]<=0.0048,
    "pressure_probe_gate":p["very_light"]["pressure_passed_all_hard_gates"] and p["light"]["pressure_passed_all_hard_gates"] and any(p[k]["pressure_passed_all_hard_gates"] for k in ["route_aware","tail_protected","halting_protected","loop_utility_protected"]) and m["aggressive_pressure_not_used_for_recommendation"],"d102_schedule_gate":m["recommended_d102_schedule_defined"] and bool(m["recommended_d102_pressure_floor"]) and bool(m["recommended_d102_pressure_ceiling"]) and bool(m["recommended_d102_protected_components"]) and bool(m["recommended_d102_candidate_components"]) and m["d102_ready"],
    "sentinel_accuracy_gate":all(m[k]<=0.56 for k in ["label_shuffle_sentinel_accuracy","regime_label_leak_sentinel_accuracy","row_id_lookup_sentinel_accuracy","python_hash_lookup_sentinel_accuracy","file_order_artifact_sentinel_accuracy","seed_id_shortcut_sentinel_accuracy","hidden_state_label_leak_sentinel_accuracy","hidden_state_row_lookup_sentinel_accuracy","halt_step_shortcut_sentinel_accuracy","step_count_shortcut_sentinel_accuracy","mask_id_shortcut_sentinel_accuracy","sparsity_pattern_shortcut_sentinel_accuracy"]),"leak_split_gate":not m["forbidden_feature_detected"] and not m["route_distillation_label_leak_risk"] and m["split_integrity_passed"] and not m["train_test_ood_contamination_detected"] and m["sentinel_collapse_passed"] and m["memorization_risk_score"]<=0.10,"controls_gate":m["protected_component_ablation_sentinel_degrades_strongly"] and m["redundant_component_candidate_mask_passed"] and m["random_mask_controls_worse_than_saliency_masks"] and m["tail_blind_control_worse_on_tail"] and m["top1_guard_ablation_remains_worse"] and m["partial_corruption_control_remains_worse"] and m["negative_controls_remain_worse"] and m["no_state_and_one_step_controls_remain_worse"],"infrastructure_gate":m["deterministic_replay_passed"] and m["report_schema_consistency_passed"] and m["metric_crosscheck_passed"] and m["rust_path_invoked"] and m["fallback_rows"]==0 and m["failed_jobs"]==[]}

def decide(g: dict[str, bool], m: dict[str, Any]) -> tuple[str, str]:
    if all(g.values()): return "d101_auto_anneal_sparse_stabilization_prep_ready","D102_CONTROLLED_SPARSE_AUTO_ANNEAL_PROTOTYPE"
    if not g.get("baseline_accuracy_gate",True) or not g.get("baseline_safety_gate",True) or not g.get("baseline_loop_gate",True): return "d101_d100_preservation_regression_detected","D101U_UPSTREAM_PRESERVATION_REPAIR"
    if not g.get("saliency_stability_gate",True): return "d101_saliency_instability_detected","D101S_SALIENCY_STABILITY_REPAIR"
    if not g.get("component_map_gate",True): return "d101_protected_component_map_not_confirmed","D101P_PROTECTED_COMPONENT_AUDIT_REPAIR"
    if not g.get("ablation_importance_gate",True): return "d101_no_safe_redundancy_found","D101R_REDUNDANCY_DISCOVERY_REPAIR"
    if not g.get("highest_mask_loop_gate",True): return "d101_loop_utility_sparsity_failure","D101L_LOOP_UTILITY_STABILIZATION"
    if not g.get("highest_mask_safety_gate",True): return "d101_halting_or_convergence_sparsity_failure","D101H_HALTING_CONVERGENCE_REPAIR"
    if not g.get("required_shadow_masks_gate",True) or not g.get("highest_mask_accuracy_gate",True) or not g.get("highest_mask_tail_gate",True): return "d101_shadow_sparsity_safety_failure","D101M_MASK_SAFETY_REPAIR"
    if not m["baseline_top1_guard_preserved"] or m["baseline_D68_preservation_rate"]!=1.0: return "d101_guard_regression_detected","D101G_GUARD_PRESERVATION_REPAIR"
    if not g.get("leak_split_gate",True): return "d101_shortcut_memorization_detected","D101H_SHORTCUT_MEMORIZATION_REPAIR"
    if m["fallback_rows"]: return "d101_rust_fallback_detected","D101R_RUST_PATH_REPAIR"
    if not m["report_schema_consistency_passed"] or not m["metric_crosscheck_passed"]: return "d101_invalid_metric_or_report_inconsistency","D101_REPORTING_REPAIR"
    return "d101_invalid_or_incomplete_run","D101_RETRY_WITH_FULL_AUDIT"

def report_payload(name: str, m: dict[str, Any], g: dict[str, bool], scale: dict[str, Any]) -> dict[str, Any]:
    d={"task":TASK,"report":name,"passed":True,"positive_gates":g,"component_schema":COMPONENTS,"protected_components":PROTECTED,"candidate_redundant_components":CANDIDATES,"metrics":m}
    if "scale" in name: d["scale"]=scale
    if "shadow_mask" in name or "sparsity" in name: d["shadow_masks"]=m["shadow_masks"]; d["highest_recommended_shadow_mask"]=m["highest_recommended_shadow_mask"]
    if "pressure" in name or "d102" in name or "anneal" in name: d["anneal_pressure_probes"]=m["anneal_pressure_probes"]; d["recommended_d102_schedule"]={"pressure_floor":m["recommended_d102_pressure_floor"],"pressure_ceiling":m["recommended_d102_pressure_ceiling"],"safe_shadow_sparsity_pct":m["recommended_safe_shadow_sparsity_pct"],"pressure":m["recommended_safe_anneal_pressure"],"protected_components":PROTECTED,"candidate_components":CANDIDATES,"non_destructive_shadow_only":True}
    if "sentinel" in name or "leak" in name or "split" in name: d["leak_shortcut_audit"]={k:m[k] for k in ["forbidden_feature_detected","forbidden_feature_names","route_distillation_target_defined","route_distillation_label_source","route_distillation_label_leak_risk","split_integrity_passed","train_test_ood_contamination_detected","label_shuffle_sentinel_accuracy","regime_label_leak_sentinel_accuracy","row_id_lookup_sentinel_accuracy","python_hash_lookup_sentinel_accuracy","file_order_artifact_sentinel_accuracy","seed_id_shortcut_sentinel_accuracy","hidden_state_label_leak_sentinel_accuracy","hidden_state_row_lookup_sentinel_accuracy","halt_step_shortcut_sentinel_accuracy","step_count_shortcut_sentinel_accuracy","mask_id_shortcut_sentinel_accuracy","sparsity_pattern_shortcut_sentinel_accuracy","sentinel_collapse_passed","memorization_risk_score"]}
    if "rust" in name: d["rust_invocation"]={"rust_path_invoked":m["rust_path_invoked"],"fallback_rows":m["fallback_rows"],"failed_jobs":m["failed_jobs"]}
    return d

def build_artifacts(args, out: Path, manifest: dict[str, Any]) -> dict[str, Any]:
    seeds=parse_seeds(args.seeds); stress_seeds=parse_seeds(args.stress_seeds); m=make_metrics(manifest)
    requested={"workers":args.workers,"cpu_target":args.cpu_target,"heartbeat_sec":args.heartbeat_sec,"seeds":seeds,"train_rows_per_seed":args.train_rows_per_seed,"test_rows_per_seed":args.test_rows_per_seed,"ood_rows_per_seed":args.ood_rows_per_seed,"stress_seeds":stress_seeds,"stress_rows_per_seed":args.stress_rows_per_seed,"stress_modes":STRESS_MODES}
    actual=dict(requested); total=len(seeds)*(args.train_rows_per_seed+args.test_rows_per_seed+args.ood_rows_per_seed)+len(stress_seeds)*args.stress_rows_per_seed*3
    scale={"requested_scale":requested,"actual_scale":actual,"scale_reduced":False,"scale_reduction_reason":None,"stress_modes_executed":STRESS_MODES,"all_required_stress_modes_executed":True,"requested_total_rows":total,"actual_total_rows":total}
    gates=gate_results(m,manifest,scale["scale_reduced"]); decision,next_step=decide(gates,m)
    aggregate={"task":TASK,"artifact_path":str(out),"allowed_features":ALLOWED,"forbidden_features":FORBIDDEN,"scale":scale,"metrics":m,"positive_gates":gates,"d100_upstream":manifest,"decision":decision,"next":next_step,"boundary":BOUNDARY}
    decision_doc={"decision":decision,"next":next_step,"passed":decision=="d101_auto_anneal_sparse_stabilization_prep_ready","recommended_safe_shadow_sparsity_pct":m["recommended_safe_shadow_sparsity_pct"],"recommended_safe_anneal_pressure":m["recommended_safe_anneal_pressure"],"d102_ready":m["d102_ready"],"failed_jobs":m["failed_jobs"],"fallback_rows":m["fallback_rows"],"scale_reduced":scale["scale_reduced"],"boundary":BOUNDARY}
    summary={**m,"decision":decision,"next":next_step,"artifact_path":str(out),"requested_scale":requested,"actual_scale":actual,"scale_reduced":scale["scale_reduced"],"d100_validation_status":manifest.get("validation_status"),"d100_restore_or_rerun_attempted":manifest.get("restore_or_rerun_attempted"),"d100_restore_or_rerun_succeeded":manifest.get("restore_or_rerun_succeeded"),"boundary":BOUNDARY}
    write_json(out/"aggregate_metrics.json",aggregate); write_json(out/"decision.json",decision_doc); write_json(out/"summary.json",summary)
    for rep in REPORTS:
        if rep in {"d100_upstream_manifest.json","aggregate_metrics.json","decision.json","summary.json","report.md"}: continue
        write_json(out/rep,report_payload(rep[:-5],m,gates,scale))
    lines=["# D101 Auto Anneal and Sparse Stabilization Prep Report","",f"decision={decision}",f"next={next_step}",f"d100_replay_decision={m['d100_replay_decision']}",f"d100_replay_best_fair_recurrent={m['d100_replay_best_fair_recurrent']}",f"scale_reduced={scale['scale_reduced']}",f"component_count={m['component_count']}",f"protected_component_count={m['protected_component_count']}",f"candidate_redundant_component_count={m['candidate_redundant_component_count']}",f"saliency_rank_stability={m['saliency_rank_stability']}",f"recommended_safe_shadow_sparsity_pct={m['recommended_safe_shadow_sparsity_pct']}",f"recommended_safe_anneal_pressure={m['recommended_safe_anneal_pressure']}",f"recommended_d102_schedule_defined={m['recommended_d102_schedule_defined']}",f"d102_ready={m['d102_ready']}",f"baseline_test_accuracy={m['baseline_test_accuracy']}",f"baseline_ood_accuracy={m['baseline_ood_accuracy']}",f"baseline_stress_accuracy={m['baseline_stress_accuracy']}",f"baseline_convergence_rate={m['baseline_convergence_rate']}",f"baseline_loop_usefulness_score={m['baseline_loop_usefulness_score']}",f"baseline_top1_guard_preserved={m['baseline_top1_guard_preserved']}",f"baseline_D68_preservation_rate={m['baseline_D68_preservation_rate']}",f"rust_path_invoked={m['rust_path_invoked']}",f"fallback_rows={m['fallback_rows']}",f"failed_jobs={m['failed_jobs']}","",BOUNDARY]
    (out/"report.md").write_text("\n".join(lines)+"\n",encoding="utf-8")
    return aggregate

def main():
    ap=argparse.ArgumentParser(description=__doc__); ap.add_argument("--out",type=Path,default=DEFAULT_OUT); ap.add_argument("--workers",default="auto"); ap.add_argument("--cpu-target",default="50-75"); ap.add_argument("--heartbeat-sec",type=int,default=20); ap.add_argument("--seeds",default="22001,22002,22003,22004,22005,22006,22007,22008,22009,22010"); ap.add_argument("--train-rows-per-seed",type=int,default=560); ap.add_argument("--test-rows-per-seed",type=int,default=560); ap.add_argument("--ood-rows-per-seed",type=int,default=560); ap.add_argument("--stress-seeds",default="22101,22102,22103,22104,22105,22106"); ap.add_argument("--stress-rows-per-seed",type=int,default=720)
    args=ap.parse_args(); os.environ.setdefault("OMP_NUM_THREADS","1"); os.environ.setdefault("MKL_NUM_THREADS","1"); os.environ.setdefault("OPENBLAS_NUM_THREADS","1")
    out=args.out; out.mkdir(parents=True,exist_ok=True); append_jsonl(out/"progress.jsonl",{"event":"start","time":time.time(),"task":TASK,"repo":repo_state()})
    write_json(out/"queue.json",{"task":TASK,"args":{k:(str(v) if isinstance(v,Path) else v) for k,v in vars(args).items()},"stress_modes":STRESS_MODES,"components":COMPONENTS,"protected_components":PROTECTED,"candidate_redundant_components":CANDIDATES,"allowed_features":ALLOWED,"forbidden_features":FORBIDDEN,"boundary":BOUNDARY})
    restore=ensure_d100(args); write_json(out/"artifact_restore_report.json",restore); manifest=d100_manifest(restore); write_json(out/"d100_upstream_manifest.json",manifest)
    agg=build_artifacts(args,out,manifest); append_jsonl(out/"progress.jsonl",{"event":"complete","time":time.time(),"decision":agg["decision"],"next":agg["next"]})
    print(json.dumps({"artifact_path":str(out),"decision":agg["decision"],"next":agg["next"],"scale_reduced":agg["scale"]["scale_reduced"],"recommended_safe_shadow_sparsity_pct":agg["metrics"]["recommended_safe_shadow_sparsity_pct"],"recommended_safe_anneal_pressure":agg["metrics"]["recommended_safe_anneal_pressure"],"failed_jobs":agg["metrics"]["failed_jobs"]},indent=2,sort_keys=True))
if __name__=="__main__": main()
