#!/usr/bin/env python3
"""Validate D102 controlled sparse auto-anneal prototype artifacts."""
from __future__ import annotations
import argparse,json,sys
from pathlib import Path
TASK="D102_CONTROLLED_SPARSE_AUTO_ANNEAL_PROTOTYPE"; D101_COMMIT="3fd46643bd52515f2f2d0bfa4ce77c6661b33993"
REPORTS="""d101_upstream_manifest.json d102_scale_report.json d102_dense_baseline_preservation_report.json d102_protected_component_lock_report.json d102_candidate_component_targeting_report.json d102_checkpoint_rollback_report.json d102_stage0_dense_replay_report.json d102_stage1_2pct_report.json d102_stage2_4pct_report.json d102_stage3_6pct_report.json d102_stage4_8pct_report.json d102_stagewise_regression_report.json d102_final_sparse_candidate_report.json d102_sparse_candidate_stability_report.json d102_sparse_mask_stability_report.json d102_sparse_recovery_report.json d102_sparse_route_distribution_report.json d102_sparse_loop_utility_report.json d102_sparse_convergence_report.json d102_sparse_halting_report.json d102_sparse_state_robustness_report.json d102_low_cost_ood_top1_ambiguity_tail_sparse_report.json d102_combined_ood_joint_boundary_carryover_report.json d102_ood_stress_scale_carryover_report.json d102_min_seed_worst_seed_sparse_report.json d102_safety_margin_sparse_report.json d102_top1_guard_sparse_report.json d102_D68_sparse_report.json d102_oracle_distance_frontier_sparse_report.json d102_support_cost_frontier_sparse_report.json d102_compression_efficiency_report.json d102_sparse_inference_cost_report.json d102_rust_sparse_invocation_report.json d102_reference_only_oversparsity_report.json d102_reference_only_pressure_report.json d102_control_mask_report.json d102_label_shuffle_sentinel_report.json d102_regime_label_leak_sentinel_report.json d102_row_id_lookup_sentinel_report.json d102_python_hash_lookup_sentinel_report.json d102_file_order_artifact_sentinel_report.json d102_seed_id_shortcut_sentinel_report.json d102_hidden_state_label_leak_sentinel_report.json d102_hidden_state_row_lookup_sentinel_report.json d102_halt_step_shortcut_sentinel_report.json d102_step_count_shortcut_sentinel_report.json d102_mask_id_shortcut_sentinel_report.json d102_sparsity_pattern_shortcut_sentinel_report.json d102_checkpoint_id_shortcut_sentinel_report.json d102_component_id_shortcut_sentinel_report.json d102_split_integrity_report.json d102_overfit_memorization_report.json d102_negative_controls_report.json d102_truth_leak_oracle_isolation_report.json d102_report_schema_metric_crosscheck_report.json d102_deterministic_replay_report.json aggregate_metrics.json decision.json summary.json report.md""".split()
def load(p): return json.loads(p.read_text(encoding="utf-8"))
def fail(msg): print(f"D102 check failed: {msg}",file=sys.stderr); sys.exit(1)
def expect(c,msg):
    if not c: fail(msg)
def stage_ok(s):
    return s["stage_non_destructive_to_baseline"] and s["protected_components_locked"] and s["protected_component_modification_count"]==0 and s["stage_checkpoint_created"] and s["stage_test_accuracy"]>=0.9940 and s["stage_ood_accuracy"]>=0.9915 and s["stage_stress_accuracy"]>=0.9910 and s["stage_min_seed_accuracy"]>=0.9905 and s["stage_worst_seed_accuracy"]>=0.9895 and s["stage_false_confidence_rate"]<=0.0046 and s["stage_routing_failure_rows"]==0 and s["stage_D68_preservation_rate"]==1.0 and s["stage_top1_guard_preserved"] and not s["stage_top1_guard_weakened"] and s["stage_convergence_rate"]>=0.998 and s["stage_non_convergence_rate"]<=0.001 and s["stage_oscillation_rate"]<=0.001 and s["stage_loop_usefulness_score"]>=0.70 and s["stage_loop_usefulness_on_tail_score"]>=0.70 and s["stage_state_stability_score"]>=0.80 and s["stage_halting_false_positive_rate"]<=0.0046 and s["stage_average_support_used"]<=6.75 and s["stage_average_steps_used"]<=5.0 and s["stage_max_steps_used"]<=8 and s["stage_passed_all_hard_gates"]
def main():
    ap=argparse.ArgumentParser(description=__doc__); ap.add_argument("--out",type=Path,required=True); args=ap.parse_args(); out=args.out
    missing=[r for r in REPORTS if not (out/r).exists()]; expect(not missing,f"missing reports: {missing}")
    agg=load(out/"aggregate_metrics.json"); dec=load(out/"decision.json"); summ=load(out/"summary.json"); man=load(out/"d101_upstream_manifest.json"); m=agg["metrics"]; g=agg["positive_gates"]
    expect(agg["task"]==TASK,"task mismatch"); expect(man["requested_d101_commit"]==D101_COMMIT,"D101 commit mismatch")
    expect(man["artifact_present"] and man["validation_status"]=="passed","D101 handoff invalid"); expect(man["replayed_decision"]=="d101_auto_anneal_sparse_stabilization_prep_ready","D101 decision mismatch"); expect(man["replayed_next"]==TASK,"D101 next mismatch"); expect(man["replayed_d102_ready"] is True,"D101 d102_ready mismatch"); expect(man["replayed_recommended_safe_shadow_sparsity_pct"]==8 and man["replayed_recommended_safe_anneal_pressure"]=="light","D101 recommendation mismatch")
    if not man.get("commit_present"): expect(man.get("restore_or_rerun_attempted") and man.get("restore_or_rerun_succeeded"),"missing D101 commit requires restore/rerun")
    expect(dec["decision"]=="d102_controlled_sparse_auto_anneal_prototype_confirmed","unexpected decision"); expect(dec["next"]=="D103_SPARSE_RECURRENT_MICROCIRCUIT_SCALE_CONFIRM","unexpected next")
    expect(dec["final_sparse_stage"]=="stage4_8pct" and dec["final_sparse_pct"]==8 and dec["final_anneal_pressure"]=="light","final sparse mismatch")
    expect(dec["failed_jobs"]==[] and dec["fallback_rows"]==0 and dec["scale_reduced"] is False,"failed/fallback/scale issue")
    expect(agg["scale"]["scale_reduced"] is False and agg["scale"]["all_required_stress_modes_executed"],"scale issue"); expect(all(g.values()),f"positive gates failed: {[k for k,v in g.items() if not v]}")
    for r in REPORTS:
        if r in {"d101_upstream_manifest.json","aggregate_metrics.json","decision.json","summary.json","report.md"}: continue
        expect(load(out/r).get("passed") is True,f"{r} not passed")
    expect(m["dense_baseline_preserved"] and m["sparse_candidate_created"] and m["sparse_candidate_is_copy"],"candidate copy/baseline failure")
    expect(m["protected_components_locked"] and m["protected_component_modification_count"]==0,"protected component violation")
    expect(m["candidate_components_targeted"] and m["candidate_component_modification_count"]>0,"candidate targeting failure")
    expect(m["rollback_enabled"] and m["checkpoint_count"]>=5 and m["failed_checkpoint_count"]==0 and not m["rollback_triggered"],"checkpoint/rollback failure")
    for name in ["stage1_2pct","stage2_4pct","stage3_6pct","stage4_8pct"]: expect(stage_ok(m["stage_metrics"][name]),f"{name} failed gates")
    for k,t in {"sparse_test_accuracy":0.9940,"sparse_ood_accuracy":0.9915,"sparse_stress_accuracy":0.9910,"sparse_min_seed_accuracy":0.9905,"sparse_worst_seed_accuracy":0.9895,"sparse_convergence_rate":0.998,"sparse_loop_usefulness_score":0.70,"sparse_loop_usefulness_on_tail_score":0.70,"sparse_state_stability_score":0.80,"sparse_low_cost_ood_top1_tail_score":0.746,"sparse_min_seed_low_cost_ood_top1_tail_score":0.742,"sparse_combined_ood_joint_boundary_breakpoint":0.755,"sparse_min_seed_combined_ood_joint_boundary_breakpoint":0.752,"sparse_external_required_accuracy":0.995,"sparse_joint_required_accuracy":0.994,"sparse_indistinguishable_abstain_rate":0.9948}.items(): expect(m[k]>=t,f"{k} below threshold")
    for k,c in {"sparse_overfit_gap":0.015,"sparse_false_confidence_rate":0.0046,"sparse_non_convergence_rate":0.001,"sparse_oscillation_rate":0.001,"sparse_halting_false_positive_rate":0.0046,"sparse_wrong_concrete_counter_rate":0.0007,"sparse_weak_top1_top2_path_failure_rate":0.0006,"sparse_top1_top2_sufficient_false_joint_rate":0.0015,"sparse_worst_tail_failure_rate":0.003,"sparse_mixed_tail_compound_failure_rate":0.004,"sparse_false_positive_confidence_tail_rate":0.0048,"sparse_distance_to_symbolic_teacher":0.025,"sparse_distance_to_d100_recurrent":0.025,"sparse_distance_to_d101_baseline":0.025,"sparse_distance_to_concrete_oracle_support":0.385,"sparse_average_support_used":6.75,"sparse_average_steps_used":5.0,"sparse_max_steps_used":8,"memorization_risk_score":0.10}.items(): expect(m[k]<=c,f"{k} above ceiling")
    expect(m["sparse_routing_failure_rows"]==0 and m["sparse_D68_preservation_rate"]==1.0 and m["sparse_top1_guard_preserved"] and not m["sparse_top1_guard_weakened"],"sparse guard failure")
    expect(m["sparse_inference_cost_reduction_pct"]>0 and 5<=m["sparse_active_component_reduction_pct"]<=8 and m["sparse_rust_path_invoked"] and m["sparse_fallback_rows"]==0 and m["sparse_failed_jobs"]==[],"sparse cost/rust failure")
    for key in ["label_shuffle_sentinel_accuracy","regime_label_leak_sentinel_accuracy","row_id_lookup_sentinel_accuracy","python_hash_lookup_sentinel_accuracy","file_order_artifact_sentinel_accuracy","seed_id_shortcut_sentinel_accuracy","hidden_state_label_leak_sentinel_accuracy","hidden_state_row_lookup_sentinel_accuracy","halt_step_shortcut_sentinel_accuracy","step_count_shortcut_sentinel_accuracy","mask_id_shortcut_sentinel_accuracy","sparsity_pattern_shortcut_sentinel_accuracy","checkpoint_id_shortcut_sentinel_accuracy","component_id_shortcut_sentinel_accuracy"]: expect(m[key]<=0.56,f"{key} shortcut too high")
    expect(not m["forbidden_feature_detected"] and not m["route_distillation_label_leak_risk"] and m["split_integrity_passed"] and not m["train_test_ood_contamination_detected"] and m["sentinel_collapse_passed"],"leak/split/sentinel failure")
    expect(m["deterministic_replay_passed"] and m["report_schema_consistency_passed"] and m["metric_crosscheck_passed"] and m["rust_path_invoked"] and m["fallback_rows"]==0 and m["failed_jobs"]==[],"infrastructure failure")
    expect(summ["decision"]==dec["decision"] and summ["next"]==dec["next"],"summary mismatch")
    print(json.dumps({"status":"passed","artifact_path":str(out),"decision":dec["decision"],"next":dec["next"],"final_sparse_stage":dec["final_sparse_stage"],"final_sparse_pct":dec["final_sparse_pct"]},indent=2,sort_keys=True))
if __name__=="__main__": main()
