#!/usr/bin/env python3
"""Validate D98 surrogate adversarial scale confirmation artifacts."""
from __future__ import annotations
import argparse, json, sys
from pathlib import Path
REPORTS=["d97_upstream_manifest.json","d98_scale_report.json","d98_surrogate_adversarial_scale_report.json","d98_surrogate_ood_scale_eval_report.json","d98_surrogate_stress_tail_scale_report.json","d98_surrogate_min_seed_scale_report.json","d98_low_cost_ood_top1_ambiguity_tail_scale_report.json","d98_combined_ood_joint_boundary_carryover_report.json","d98_feature_noise_robustness_report.json","d98_feature_dropout_robustness_report.json","d98_feature_corruption_robustness_report.json","d98_feature_ablation_scale_report.json","d98_calibration_pressure_report.json","d98_confidence_false_positive_report.json","d98_top1_guard_preservation_report.json","d98_top1_guard_ablation_control_report.json","d98_top1_guard_partial_corruption_control_report.json","d98_D68_preservation_report.json","d98_safety_margin_report.json","d98_oracle_distance_frontier_report.json","d98_support_cost_frontier_report.json","d98_label_shuffle_sentinel_report.json","d98_regime_label_leak_sentinel_report.json","d98_row_id_lookup_sentinel_report.json","d98_python_hash_lookup_sentinel_report.json","d98_file_order_artifact_sentinel_report.json","d98_seed_id_shortcut_sentinel_report.json","d98_split_integrity_report.json","d98_overfit_memorization_report.json","d98_feature_importance_stability_report.json","d98_negative_controls_report.json","d98_truth_leak_oracle_isolation_report.json","d98_rust_invocation_report.json","d98_report_schema_metric_crosscheck_report.json","d98_deterministic_replay_report.json","aggregate_metrics.json","decision.json","summary.json","report.md"]
ALLOWED={"d98_surrogate_adversarial_scale_confirmed","d98_surrogate_tail_risk_detected","d98_surrogate_feature_robustness_failure","d98_surrogate_calibration_failure","top1_guard_invariant_violation","d68_regression_detected","d98_truth_leak_or_oracle_contamination_detected","d98_shortcut_memorization_detected","d98_split_contamination_detected","d98_rust_fallback_detected","d98_invalid_metric_or_report_inconsistency","d98_invalid_or_incomplete_run"}
def load(p:Path): return json.loads(p.read_text(encoding="utf-8"))
def fail(m): print(f"D98 check failed: {m}",file=sys.stderr); sys.exit(1)
def main():
    p=argparse.ArgumentParser(); p.add_argument("--out",default="target/pilot_wave/d98_surrogate_adversarial_scale_confirm"); args=p.parse_args(); out=Path(args.out)
    missing=[r for r in REPORTS if not (out/r).exists()]
    if missing: fail(f"missing reports {missing}")
    man=load(out/"d97_upstream_manifest.json"); agg=load(out/"aggregate_metrics.json"); dec=load(out/"decision.json"); summ=load(out/"summary.json"); m=agg.get("metrics",{})
    if dec.get("decision") not in ALLOWED: fail(f"bad decision {dec.get('decision')}")
    if dec.get("decision")!="d98_surrogate_adversarial_scale_confirmed": fail(f"unexpected decision {dec.get('decision')}")
    if dec.get("next")!="D99_RECURRENT_ROUTING_MICROCIRCUIT_PROTOTYPE": fail(f"unexpected next {dec.get('next')}")
    if dec.get("failed_jobs") or agg.get("failed_jobs") or m.get("failed_jobs"): fail("failed_jobs present")
    if dec.get("fallback_rows")!=0 or agg.get("fallback_rows")!=0 or m.get("fallback_rows")!=0: fail("fallback rows nonzero")
    d97=man.get("d97_artifacts",{})
    if man.get("requested_d97_commit")!="082081517b755bc57b1dd271b53435b469f06c26": fail("requested D97 commit mismatch")
    if not man.get("commit_present") and not (man.get("restore_or_rerun_attempted") and man.get("restore_or_rerun_succeeded")): fail("D97 commit missing without successful restore/rerun")
    if not man.get("artifact_present") or man.get("validation_status")!="passed": fail("D97 artifact/validation failed")
    if d97.get("decision")!="d97_surrogate_training_prototype_confirmed" or d97.get("next")!="D98_SURROGATE_ADVERSARIAL_SCALE_CONFIRM": fail("D97 handoff mismatch")
    if d97.get("best_fair_surrogate_arm")!="SURROGATE_SMALL_MLP_FAIR": fail("D97 best fair surrogate mismatch")
    gates=agg.get("positive_gates",{}); failed=[k for k,v in gates.items() if not v]
    if failed: fail(f"positive gates failed {failed}")
    for r in REPORTS:
        if r.endswith(".json") and r not in {"aggregate_metrics.json","decision.json","summary.json","d97_upstream_manifest.json"} and not load(out/r).get("passed",True): fail(f"{r} did not pass")
    checks={"best_arm":m.get("best_fair_surrogate_arm")=="SURROGATE_SMALL_MLP_FAIR","test":m.get("surrogate_scale_test_accuracy",0)>=0.994,"ood":m.get("surrogate_scale_ood_accuracy",0)>=0.9915,"stress":m.get("surrogate_scale_stress_accuracy",0)>=0.991,"min_seed":m.get("surrogate_scale_min_seed_accuracy",0)>=0.9905,"worst_seed":m.get("surrogate_scale_worst_seed_accuracy",0)>=0.9895,"overfit":m.get("surrogate_scale_overfit_gap",1)<=0.015,"false_conf":m.get("surrogate_scale_false_confidence_rate",1)<=0.0046,"routing":m.get("surrogate_scale_routing_failure_rows")==0,"D68":m.get("surrogate_scale_D68_preservation_rate")==1.0,"top1":m.get("surrogate_scale_top1_guard_preserved") is True and m.get("surrogate_scale_top1_guard_weakened") is False,"truth":m.get("surrogate_scale_truth_leak_audit_passed") is True,"oracle":m.get("surrogate_scale_oracle_isolation_passed") is True,"teacher_distance":m.get("surrogate_scale_distance_to_symbolic_teacher",1)<=0.025,"oracle_distance":m.get("surrogate_scale_distance_to_concrete_oracle_support",1)<=0.385,"support":m.get("surrogate_scale_average_support_used",99)<=6.75,"tail":m.get("surrogate_scale_combined_low_cost_ood_top1_ambiguity_tail_score",0)>=0.744,"min_tail":m.get("surrogate_scale_min_seed_low_cost_ood_top1_ambiguity_tail_score",0)>=0.740,"combined":m.get("surrogate_scale_combined_ood_joint_boundary_breakpoint",0)>=0.755,"min_combined":m.get("surrogate_scale_min_seed_combined_ood_joint_boundary_breakpoint",0)>=0.752,"external":m.get("surrogate_scale_external_required_accuracy",0)>=0.995,"joint":m.get("surrogate_scale_joint_required_accuracy",0)>=0.994,"abstain":m.get("surrogate_scale_indistinguishable_abstain_rate",0)>=0.9948,"wrong":m.get("surrogate_scale_wrong_concrete_counter_rate",1)<=0.0007,"weak":m.get("surrogate_scale_weak_top1_top2_path_failure_rate",1)<=0.0006,"false_joint":m.get("surrogate_scale_top1_top2_sufficient_false_joint_rate",1)<=0.0015,"noise1":m.get("feature_noise_1pct_accuracy",0)>=0.991,"noise3":m.get("feature_noise_3pct_accuracy",0)>=0.988,"noise5":m.get("feature_noise_5pct_accuracy",0)>=0.985,"noise_false":m.get("feature_noise_5pct_false_confidence_rate",1)<=0.0048,"drop1":m.get("feature_dropout_1_signal_accuracy",0)>=0.989,"drop2":m.get("feature_dropout_2_signals_accuracy",0)>=0.985,"dropr":m.get("feature_dropout_random_10pct_accuracy",0)>=0.985,"corrupt":m.get("feature_corruption_failure_rate",1)<=0.003,"calib":m.get("calibration_strict_false_confidence_rate",1)<=0.0044,"fp_tail":m.get("false_positive_confidence_tail_rate",1)<=0.0048,"worst_tail":m.get("worst_tail_failure_rate",1)<=0.003,"mixed":m.get("mixed_tail_compound_failure_rate",1)<=0.004,"sentinel":m.get("sentinel_collapse_passed") is True,"memorization":m.get("memorization_risk_score",1)<=0.10,"feature_stability":m.get("feature_importance_stability_scale",0)>=0.70,"rust":m.get("rust_path_invoked") is True,"fallback":m.get("fallback_rows")==0,"failed_jobs":m.get("failed_jobs")==[]}
    bad=[k for k,v in checks.items() if not v]
    if bad: fail(f"metric gates failed {bad}")
    if m.get("forbidden_feature_detected") or m.get("forbidden_feature_names") or m.get("route_distillation_label_leak_risk") or not m.get("split_integrity_passed") or m.get("train_test_ood_contamination_detected"): fail("feature/distillation/split audit failed")
    sentinel_limits={"label_shuffle_sentinel_accuracy":0.55,"regime_label_leak_sentinel_accuracy":0.56,"row_id_lookup_sentinel_accuracy":0.55,"python_hash_lookup_sentinel_accuracy":0.55,"file_order_artifact_sentinel_accuracy":0.55,"seed_id_shortcut_sentinel_accuracy":0.55}
    if [k for k,v in sentinel_limits.items() if m.get(k,1)>v]: fail("sentinel shortcut failed")
    if summ.get("decision")!=dec.get("decision") or summ.get("next")!=dec.get("next") or summ.get("best_fair_surrogate_arm")!=m.get("best_fair_surrogate_arm"): fail("summary mismatch")
    print(json.dumps({"check":"passed","out":str(out),"decision":dec,"best_fair_surrogate_arm":m.get("best_fair_surrogate_arm"),"surrogate_scale_test_accuracy":m.get("surrogate_scale_test_accuracy"),"failed_jobs":m.get("failed_jobs")},indent=2))
if __name__=="__main__": main()
