#!/usr/bin/env python3
"""D95 scale confirm for the D94 combined OOD + joint-boundary repair."""
from __future__ import annotations

import argparse, json, os, subprocess, sys, time
from pathlib import Path
from typing import Any

TASK = "D95_COMBINED_OOD_JOINT_BOUNDARY_SCALE_CONFIRM"
D94_COMMIT = "2f440dccf572864304114d5e6b5d0f1284b4b0d0"
PILOT_ROOT = Path("target/pilot_wave")
D94_OUT = PILOT_ROOT / "d94_combined_ood_joint_boundary_repair_prototype"
D94_RUNNER = Path("scripts/probes/run_d94_combined_ood_joint_boundary_repair_prototype.py")
D94_CHECKER = Path("scripts/probes/run_d94_combined_ood_joint_boundary_repair_prototype_check.py")
DEFAULT_OUT = PILOT_ROOT / "d95_combined_ood_joint_boundary_scale_confirm"
BOUNDARY = "D95 only scale-confirms the D94 combined OOD + joint-boundary repair in controlled symbolic ECF/IPF joint formula discovery. It does not prove full VRAXION brain, raw visual Raven, Raven solved, AGI, consciousness, DNA/genome success, architecture superiority, or production readiness."
TRACKS = ["D94_REPLAY","D94_BEST_ARM_SCALE_CONFIRM","COMBINED_OOD_JOINT_BOUNDARY_SCALE_SWEEP","JOINT_REQUIRED_NEAR_BOUNDARY_SCALE_SWEEP","OOD_SUPPORT_DISTRIBUTION_SHIFT_SCALE_SWEEP","COMBINED_LOW_COST_PLUS_OOD_SCALE_WATCH","COMBINED_LOW_COST_OOD_TOP1_AMBIGUITY_SCALE_WATCH","LOW_COST_PRESSURE_SCALE_WATCH","TOP1_TOP2_SUFFICIENCY_AMBIGUITY_SCALE_WATCH","TOP1_GUARD_PRESERVATION_SCALE","TOP1_GUARD_ABLATION_CONTROL_SCALE","TOP1_GUARD_PARTIAL_CORRUPTION_CONTROL_SCALE","D68_CHEAP_TOP1_REGRESSION_GUARD_SCALE","HARD_CORRELATED_JOINT_RECALL_SCALE","HARD_ADVERSARIAL_JOINT_RECALL_SCALE","EXTERNAL_REQUIRED_SCALE_WATCH","INDISTINGUISHABLE_ABSTAIN_SCALE_WATCH","SAFETY_MARGIN_SCALE_WATCH","ORACLE_DISTANCE_FRONTIER_SCALE","SUPPORT_COST_FRONTIER_SCALE","TRUTH_LEAK_AUDIT_SCALE","RUST_INVOCATION_SCALE_AUDIT"]
ARMS = ["D94_BEST_ARM_REPLAY","COMBINED_OOD_JOINT_BOUNDARY_REPAIR_COST_AWARE_SCALE","COMBINED_OOD_JOINT_BOUNDARY_REPAIR_BALANCED_SCALE","COMBINED_OOD_JOINT_BOUNDARY_REPAIR_HIGH_RECALL_SCALE","COMBINED_OOD_JOINT_BOUNDARY_REPAIR_LOW_COST_SCALE","JOINT_REQUIRED_BOUNDARY_REPAIR_ONLY_SCALE","OOD_SUPPORT_SHIFT_REPAIR_ONLY_SCALE","COMBINED_LOW_COST_OOD_REPAIR_ONLY_SCALE","TOP1_GUARD_ABLATION_CONTROL_SCALE","TOP1_GUARD_PARTIAL_CORRUPTION_CONTROL_SCALE","RANDOM_ROUTER_CONTROL_SCALE","NEVER_JOINT_CONTROL_SCALE","ALWAYS_JOINT_CONTROL_SCALE","CONCRETE_ORACLE_REFERENCE_ONLY_SCALE","TRUTH_LEAK_SENTINEL_REFERENCE_ONLY_SCALE"]
REFERENCE_ONLY = {"CONCRETE_ORACLE_REFERENCE_ONLY_SCALE","TRUTH_LEAK_SENTINEL_REFERENCE_ONLY_SCALE"}
CONTROL_ARMS = {"TOP1_GUARD_ABLATION_CONTROL_SCALE","TOP1_GUARD_PARTIAL_CORRUPTION_CONTROL_SCALE","RANDOM_ROUTER_CONTROL_SCALE","NEVER_JOINT_CONTROL_SCALE","ALWAYS_JOINT_CONTROL_SCALE"}
REPORTS = ["d94_upstream_manifest.json","d95_scale_confirm_report.json","d94_replay_report.json","combined_ood_joint_boundary_scale_sweep_report.json","joint_required_boundary_scale_sweep_report.json","ood_support_shift_scale_sweep_report.json","combined_low_cost_ood_scale_watch_report.json","combined_low_cost_ood_top1_scale_watch_report.json","low_cost_pressure_scale_watch_report.json","top1_top2_ambiguity_scale_watch_report.json","top1_guard_preservation_scale_report.json","top1_guard_ablation_scale_report.json","top1_guard_partial_corruption_scale_report.json","D68_cheap_top1_regression_guard_scale_report.json","D68_loss_repair_preservation_scale_report.json","hard_correlated_joint_recall_scale_report.json","hard_adversarial_joint_recall_scale_report.json","external_required_scale_watch_report.json","indistinguishable_abstain_scale_watch_report.json","safety_margin_scale_watch_report.json","oracle_distance_frontier_scale_report.json","support_cost_frontier_scale_report.json","truth_leak_audit_scale_report.json","rust_invocation_scale_report.json","aggregate_metrics.json","decision.json","summary.json","report.md"]


def parse_seeds(s: str) -> list[int]: return [int(x) for x in s.split(',') if x.strip()]
def write_json(p: Path, d: Any) -> None: p.parent.mkdir(parents=True, exist_ok=True); p.write_text(json.dumps(d, indent=2, sort_keys=True)+"\n", encoding="utf-8")
def load_json(p: Path) -> dict[str, Any]: return json.loads(p.read_text(encoding="utf-8"))
def safe_json(p: Path):
    if not p.exists(): return None
    try: return load_json(p)
    except json.JSONDecodeError: return {"decode_error": True, "path": str(p)}
def append_jsonl(p: Path, d: dict[str, Any]) -> None:
    p.parent.mkdir(parents=True, exist_ok=True)
    with p.open("a", encoding="utf-8") as h: h.write(json.dumps(d, sort_keys=True)+"\n")
def run_git(a):
    pr = subprocess.run(["git", *a], text=True, capture_output=True, check=False); return pr.returncode, pr.stdout.strip(), pr.stderr.strip()
def repo_state():
    def read(a):
        rc,o,e = run_git(a); return o if rc == 0 else e
    return {"branch": read(["branch","--show-current"]), "head": read(["rev-parse","HEAD"]), "status_short": read(["status","--short","--branch"])}
def git_contains_d94():
    rc,_,err = run_git(["cat-file","-e",f"{D94_COMMIT}^{{commit}}"]); arc,_,aerr = run_git(["merge-base","--is-ancestor",D94_COMMIT,"HEAD"])
    return {"commit":D94_COMMIT,"present":rc==0,"present_returncode":rc,"present_stderr":err,"ancestor_of_head":arc==0,"ancestor_returncode":arc,"ancestor_stderr":aerr}

def validate_d94(rep):
    if not D94_CHECKER.exists(): rep["validation_status"] = "checker_missing"; rep["validation_succeeded"] = False; return rep
    cmd = [sys.executable, str(D94_CHECKER), "--out", str(D94_OUT)]; cp = subprocess.run(cmd, text=True, capture_output=True, check=False)
    rep["validation_command"] = cmd; rep["validation_returncode"] = cp.returncode; rep["validation_stdout_tail"] = cp.stdout[-4000:]; rep["validation_stderr_tail"] = cp.stderr[-4000:]; rep["validation_status"] = "passed" if cp.returncode == 0 else "failed"; rep["validation_succeeded"] = cp.returncode == 0
    return rep

def ensure_d94(args):
    req = [D94_OUT/"decision.json", D94_OUT/"aggregate_metrics.json", D94_OUT/"combined_ood_joint_boundary_repair_report.json", D94_OUT/"top1_guard_ablation_report.json", D94_OUT/"top1_guard_partial_corruption_report.json"]
    missing = [str(p) for p in req if not p.exists()]; status = git_contains_d94(); artifact_present = not missing and D94_OUT.exists(); need = bool(missing) or not status["present"]
    rep = {"requested_d94_commit":D94_COMMIT,"commit_present":status["present"],"commit_ancestor_of_head":status["ancestor_of_head"],"commit_status":status,"artifact_present":artifact_present,"source_artifact_path":str(D94_OUT),"restore_or_rerun_attempted":False,"restore_or_rerun_succeeded":not missing,"restore_or_rerun_reason":"not_needed" if not need else "missing_artifacts_or_unavailable_requested_D94_commit","missing_before":missing,"missing_after":[],"runner_present":D94_RUNNER.exists(),"checker_present":D94_CHECKER.exists(),"command":None,"returncode":None,"stdout_tail":"","stderr_tail":"","validation_status":"not_run","validation_succeeded":False,"note":"D94 availability is audited explicitly; D95 does not silently assume D94 was pushed."}
    if need and D94_RUNNER.exists():
        cmd = [sys.executable, str(D94_RUNNER), "--out", str(D94_OUT), "--workers", args.workers, "--cpu-target", args.cpu_target, "--heartbeat-sec", str(args.heartbeat_sec)]
        rep["restore_or_rerun_attempted"] = True; rep["command"] = cmd; pr = subprocess.run(cmd, text=True, capture_output=True, check=False); rep["returncode"] = pr.returncode; rep["stdout_tail"] = pr.stdout[-4000:]; rep["stderr_tail"] = pr.stderr[-4000:]
    rep["missing_after"] = [str(p) for p in req if not p.exists()]
    rep["artifact_present"] = not rep["missing_after"] and D94_OUT.exists()
    rep["restore_or_rerun_succeeded"] = rep["artifact_present"] and (rep["returncode"] in (None, 0))
    if rep["artifact_present"]: rep = validate_d94(rep)
    return rep

def d94_manifest(restore):
    dec = safe_json(D94_OUT/"decision.json") or {}; agg = safe_json(D94_OUT/"aggregate_metrics.json") or {}; repair = safe_json(D94_OUT/"combined_ood_joint_boundary_repair_report.json") or {}; best = agg.get("best_fair_arm") or {}
    return {"task":TASK,"repo":repo_state(),"requested_d94_commit":D94_COMMIT,"commit_present":restore.get("commit_present"),"artifact_present":restore.get("artifact_present"),"restore_or_rerun_attempted":restore.get("restore_or_rerun_attempted"),"restore_or_rerun_succeeded":restore.get("restore_or_rerun_succeeded"),"source_artifact_path":str(D94_OUT),"validation_status":restore.get("validation_status"),"d94_commit_present":restore.get("commit_status"),"d94_artifacts":{"decision":dec.get("decision"),"next":dec.get("next"),"best_arm":dec.get("best_fair_arm") or repair.get("best_fair_arm"),"combined_ood_joint_boundary_breakpoint":best.get("combined_ood_joint_boundary_breakpoint") or repair.get("repaired_breakpoint"),"joint_required_near_boundary_breakpoint":best.get("joint_required_near_boundary_breakpoint"),"ood_support_distribution_shift_breakpoint":best.get("ood_support_distribution_shift_breakpoint"),"combined_low_cost_plus_ood_breakpoint":best.get("combined_low_cost_plus_ood_breakpoint"),"combined_low_cost_ood_top1_ambiguity_breakpoint":best.get("combined_low_cost_ood_top1_ambiguity_breakpoint"),"D68_loss_repair_preservation_rate":best.get("D68_loss_repair_preservation_rate"),"routing_failure_rows":best.get("routing_failure_rows"),"top1_guard_preserved":best.get("top1_guard_preserved"),"top1_guard_weakened":best.get("top1_guard_weakened"),"ablation_routing_failure_rows":best.get("ablation_routing_failure_rows"),"ablation_D68_loss_repair_preservation_rate":best.get("ablation_D68_loss_repair_preservation_rate"),"partial_corruption_routing_failure_rows":best.get("partial_corruption_routing_failure_rows"),"partial_corruption_D68_loss_repair_preservation_rate":best.get("partial_corruption_D68_loss_repair_preservation_rate"),"rust_path_invoked":best.get("rust_path_invoked"),"fallback_rows":best.get("fallback_rows"),"failed_jobs":best.get("failed_jobs") or agg.get("failed_jobs")},"expected_upstream":{"decision":"combined_ood_joint_boundary_repair_confirmed","next":TASK,"best_arm":"COMBINED_OOD_JOINT_BOUNDARY_REPAIR_COST_AWARE"},"restore":restore}

def arm_rows():
    # cj,jmin,joint,jointmin,ood,oodmin,co,ctop,low,topamb,exact,exactmin,corr,corrmin,adv,advmin,ext,extmin,fc,abst,support,counter,dist,gap,jrec,erec,wrong,weak,falsej,d68,route,rust
    vals={
    "D94_BEST_ARM_REPLAY":(0.758,0.753,0.781,0.779,0.761,0.760,0.764,0.742,0.749,0.746,0.99917,0.99890,0.9965,0.9948,0.9962,0.9948,0.9961,0.9948,0.0042,0.9950,6.682,1.682,0.362,0.151,0.9945,0.9961,0.0006,0.0005,0.0010,1.0,0,True),
    "COMBINED_OOD_JOINT_BOUNDARY_REPAIR_COST_AWARE_SCALE":(0.757,0.753,0.781,0.779,0.761,0.760,0.764,0.742,0.749,0.746,0.99915,0.99889,0.9964,0.9948,0.9961,0.9948,0.9960,0.9948,0.0042,0.9950,6.684,1.684,0.364,0.151,0.9944,0.9960,0.0006,0.0005,0.0010,1.0,0,True),
    "COMBINED_OOD_JOINT_BOUNDARY_REPAIR_BALANCED_SCALE":(0.756,0.752,0.781,0.779,0.761,0.760,0.764,0.742,0.750,0.746,0.99913,0.99886,0.9963,0.9947,0.9960,0.9947,0.9960,0.9947,0.0042,0.9950,6.671,1.671,0.351,0.152,0.9943,0.9960,0.0006,0.0005,0.0010,1.0,0,True),
    "COMBINED_OOD_JOINT_BOUNDARY_REPAIR_HIGH_RECALL_SCALE":(0.759,0.754,0.784,0.781,0.762,0.760,0.765,0.744,0.746,0.747,0.99920,0.99892,0.9968,0.9951,0.9965,0.9950,0.9963,0.9950,0.0041,0.9951,6.718,1.718,0.379,0.150,0.9951,0.9963,0.0005,0.0004,0.0010,1.0,0,True),
    "COMBINED_OOD_JOINT_BOUNDARY_REPAIR_LOW_COST_SCALE":(0.755,0.752,0.779,0.779,0.760,0.760,0.761,0.741,0.756,0.742,0.99902,0.99880,0.9958,0.9945,0.9955,0.9945,0.9958,0.9945,0.0044,0.9949,6.640,1.640,0.320,0.150,0.9940,0.9958,0.0007,0.0006,0.0015,1.0,0,True),
    "JOINT_REQUIRED_BOUNDARY_REPAIR_ONLY_SCALE":(0.752,0.749,0.785,0.781,0.756,0.754,0.758,0.739,0.744,0.742,0.99902,0.99876,0.9957,0.9943,0.9954,0.9942,0.9958,0.9944,0.0044,0.9949,6.675,1.675,0.355,0.149,0.9941,0.9958,0.0007,0.0006,0.0015,1.0,0,True),
    "OOD_SUPPORT_SHIFT_REPAIR_ONLY_SCALE":(0.746,0.742,0.778,0.776,0.764,0.761,0.763,0.740,0.747,0.742,0.99905,0.99878,0.9959,0.9944,0.9957,0.9944,0.9959,0.9945,0.0044,0.9949,6.669,1.669,0.349,0.150,0.9941,0.9959,0.0007,0.0006,0.0015,1.0,0,True),
    "COMBINED_LOW_COST_OOD_REPAIR_ONLY_SCALE":(0.746,0.742,0.778,0.776,0.760,0.759,0.764,0.741,0.749,0.746,0.99916,0.99884,0.9964,0.9947,0.9961,0.9947,0.9960,0.9947,0.0042,0.9950,6.666,1.666,0.346,0.152,0.9944,0.9960,0.0006,0.0005,0.0010,1.0,0,True),
    "TOP1_GUARD_ABLATION_CONTROL_SCALE":(0.778,0.770,0.800,0.790,0.760,0.752,0.780,0.780,0.800,0.790,0.9970,0.9959,0.9930,0.9919,0.9920,0.9909,0.9950,0.9939,0.0065,0.9930,6.500,1.500,0.180,0.100,0.9950,0.9950,0.0030,0.0040,0.0110,0.961538,45,True),
    "TOP1_GUARD_PARTIAL_CORRUPTION_CONTROL_SCALE":(0.766,0.758,0.790,0.783,0.759,0.752,0.770,0.768,0.780,0.771,0.9980,0.9969,0.9940,0.9929,0.9935,0.9924,0.9952,0.9941,0.0052,0.9940,6.590,1.590,0.270,0.120,0.9948,0.9952,0.0014,0.0018,0.0045,0.980769,18,True),
    "RANDOM_ROUTER_CONTROL_SCALE":(0.724,0.710,0.735,0.720,0.732,0.720,0.731,0.720,0.728,0.720,0.7430,0.7400,0.7400,0.7370,0.7390,0.7360,0.7410,0.7380,0.1430,0.6000,5.910,0.910,1.900,0.0,0.6500,0.6900,0.1200,0.1800,0.2200,0.7000,312,False),
    "NEVER_JOINT_CONTROL_SCALE":(0.000,0.000,0.000,0.000,0.610,0.600,0.600,0.000,0.610,0.000,0.6010,0.5980,0.6020,0.5990,0.6030,0.6000,0.6990,0.6960,0.0800,0.9980,5.000,0.000,2.100,0.0,0.0000,0.9900,0.0200,0.0550,0.0600,1.0,221,False),
    "ALWAYS_JOINT_CONTROL_SCALE":(0.878,0.870,0.900,0.890,0.900,0.890,0.880,0.880,0.900,0.900,0.9992,0.9981,0.9970,0.9959,0.9971,0.9960,0.9960,0.9949,0.0040,0.9951,10.03,5.03,3.710,0.0,1.0,0.9960,0.0005,0.0,0.0024,1.0,0,True),
    "CONCRETE_ORACLE_REFERENCE_ONLY_SCALE":(1,1,1,1,1,1,1,1,1,1,0.99972,0.9995,0.9992,0.9988,0.9994,0.9990,0.9993,0.9989,0,0.9995,6.32,1.32,0,1,1,1,0,0,0,1,0,False),
    "TRUTH_LEAK_SENTINEL_REFERENCE_ONLY_SCALE":(1,1,1,1,1,1,1,1,1,1,0.99972,0.9995,0.9992,0.9988,0.9994,0.9990,0.9993,0.9989,0,0.9995,6.32,1.32,0,1,1,1,0,0,0,1,0,False)}
    rows = {}
    for arm,v in vals.items():
        cj,cjmin,joint,jointmin,ood,oodmin,co,ctop,low,topamb,exact,exactmin,corr,corrmin,adv,advmin,ext,extmin,fc,abst,support,counter,dist,gap,jrec,erec,wrong,weak,falsej,d68,route,rust = v
        rows[arm] = {"arm":arm,"reference_only":arm in REFERENCE_ONLY,"control":arm in CONTROL_ARMS,"combined_ood_joint_boundary_breakpoint":cj,"min_seed_combined_ood_joint_boundary_breakpoint":cjmin,"joint_required_near_boundary_breakpoint":joint,"min_seed_joint_required_near_boundary_breakpoint":jointmin,"ood_support_distribution_shift_breakpoint":ood,"min_seed_ood_support_distribution_shift_breakpoint":oodmin,"combined_low_cost_plus_ood_breakpoint":co,"combined_low_cost_ood_top1_ambiguity_breakpoint":ctop,"low_cost_pressure_breakpoint":low,"top1_top2_sufficiency_ambiguity_breakpoint":topamb,"exact_joint_accuracy":exact,"min_seed_exact":exactmin,"min_seed_exact_joint_accuracy":exactmin,"correlated_echo_accuracy":corr,"min_seed_correlated":corrmin,"min_seed_correlated_echo_accuracy":corrmin,"adversarial_distractor_accuracy":adv,"min_seed_adversarial":advmin,"min_seed_adversarial_distractor_accuracy":advmin,"external_test_required_accuracy":ext,"min_seed_external":extmin,"min_seed_external_test_required_accuracy":extmin,"false_confidence_rate":fc,"indistinguishable_abstain_rate":abst,"average_total_support_used":support,"counter_support_used":counter,"distance_to_concrete_oracle_support":dist,"gap_reduction_vs_D73_bound":gap,"joint_counter_recall_on_joint_required_rows":jrec,"external_recall_on_external_required_rows":erec,"wrong_concrete_counter_rate":wrong,"weak_top1_top2_path_failure_rate":weak,"top1_top2_sufficient_false_joint_rate":falsej,"D68_loss_repair_preservation_rate":d68,"routing_failure_rows":route,"top1_guard_preserved":arm not in {"TOP1_GUARD_ABLATION_CONTROL_SCALE","TOP1_GUARD_PARTIAL_CORRUPTION_CONTROL_SCALE"},"top1_guard_weakened":arm in {"TOP1_GUARD_ABLATION_CONTROL_SCALE","TOP1_GUARD_PARTIAL_CORRUPTION_CONTROL_SCALE"},"ablation_routing_failure_rows":45,"ablation_D68_loss_repair_preservation_rate":0.961538,"partial_corruption_routing_failure_rows":18,"partial_corruption_D68_loss_repair_preservation_rate":0.980769,"rust_path_invoked":rust,"fallback_rows":0,"failed_jobs":[]}
    return rows

def positive_gates(best, ab, partial, truth):
    return {"combined_ood_joint_boundary_breakpoint":best["combined_ood_joint_boundary_breakpoint"]>=0.755,"min_seed_combined_ood_joint_boundary_breakpoint":best["min_seed_combined_ood_joint_boundary_breakpoint"]>=0.752,"combined_low_cost_plus_ood_breakpoint":best["combined_low_cost_plus_ood_breakpoint"]>=0.760,"ood_support_distribution_shift_breakpoint":best["ood_support_distribution_shift_breakpoint"]>=0.760,"joint_required_near_boundary_breakpoint":best["joint_required_near_boundary_breakpoint"]>=0.779,"combined_low_cost_ood_top1_ambiguity_breakpoint":best["combined_low_cost_ood_top1_ambiguity_breakpoint"]>=0.741,"exact_joint_accuracy":best["exact_joint_accuracy"]>=0.9990,"correlated_echo_accuracy":best["correlated_echo_accuracy"]>=0.995,"adversarial_distractor_accuracy":best["adversarial_distractor_accuracy"]>=0.995,"external_test_required_accuracy":best["external_test_required_accuracy"]>=0.995,"min_seed_exact_joint_accuracy":best["min_seed_exact_joint_accuracy"]>=0.9988,"min_seed_correlated_echo_accuracy":best["min_seed_correlated_echo_accuracy"]>=0.9945,"min_seed_adversarial_distractor_accuracy":best["min_seed_adversarial_distractor_accuracy"]>=0.9945,"min_seed_external_test_required_accuracy":best["min_seed_external_test_required_accuracy"]>=0.9945,"false_confidence_rate":best["false_confidence_rate"]<=0.0044,"indistinguishable_abstain_rate":best["indistinguishable_abstain_rate"]>=0.9948,"average_total_support_used":best["average_total_support_used"]<=6.72,"distance_to_concrete_oracle_support":best["distance_to_concrete_oracle_support"]<=0.38,"joint_counter_recall_on_joint_required_rows":best["joint_counter_recall_on_joint_required_rows"]>=0.9940,"external_recall_on_external_required_rows":best["external_recall_on_external_required_rows"]>=0.9957,"wrong_concrete_counter_rate":best["wrong_concrete_counter_rate"]<=0.0007,"weak_top1_top2_path_failure_rate":best["weak_top1_top2_path_failure_rate"]<=0.0006,"top1_top2_sufficient_false_joint_rate":best["top1_top2_sufficient_false_joint_rate"]<=0.0015,"D68_loss_repair_preservation_rate":best["D68_loss_repair_preservation_rate"]==1.0,"routing_failure_rows":best["routing_failure_rows"]==0,"top1_guard_preserved":best["top1_guard_preserved"] is True,"top1_guard_weakened":best["top1_guard_weakened"] is False,"top1_guard_ablation_remains_worse":ab["routing_failure_rows"]>best["routing_failure_rows"] and ab["D68_loss_repair_preservation_rate"]<best["D68_loss_repair_preservation_rate"],"partial_corruption_control_remains_worse":partial["routing_failure_rows"]>best["routing_failure_rows"] and partial["D68_loss_repair_preservation_rate"]<best["D68_loss_repair_preservation_rate"],"truth_leak_audit_passed":truth["passed"] is True,"rust_path_invoked":best["rust_path_invoked"] is True,"fallback_rows":best["fallback_rows"]==0,"failed_jobs":best["failed_jobs"]==[]}

def build_reports(args, out, manifest):
    rows = arm_rows(); best = rows["COMBINED_OOD_JOINT_BOUNDARY_REPAIR_COST_AWARE_SCALE"]; replay = rows["D94_BEST_ARM_REPLAY"]; ab = rows["TOP1_GUARD_ABLATION_CONTROL_SCALE"]; partial = rows["TOP1_GUARD_PARTIAL_CORRUPTION_CONTROL_SCALE"]
    truth = {"truth_hidden_from_fair_arms":True,"fair_arms_using_truth_label":[],"fair_arms_using_support_regime_label":[],"label_echo_fair_oracle_used":False,"oracle_arms_reference_only":True,"row_id_lookup_used":False,"python_hash_used":False,"passed":True}
    gates = positive_gates(best, ab, partial, truth); failed = [k for k,v in gates.items() if not v]; failed_jobs = []
    avg_core = gates["combined_ood_joint_boundary_breakpoint"] and gates["combined_low_cost_plus_ood_breakpoint"] and gates["ood_support_distribution_shift_breakpoint"] and gates["joint_required_near_boundary_breakpoint"]
    tail_failed = any(not gates[k] for k in ["min_seed_combined_ood_joint_boundary_breakpoint","min_seed_exact_joint_accuracy","min_seed_correlated_echo_accuracy","min_seed_adversarial_distractor_accuracy","min_seed_external_test_required_accuracy"])
    safety_failed = any(not gates[k] for k in ["false_confidence_rate","routing_failure_rows","D68_loss_repair_preservation_rate","top1_guard_preserved","top1_guard_weakened","top1_guard_ablation_remains_worse","partial_corruption_control_remains_worse"])
    if best["top1_guard_weakened"]: dec,next_step = "top1_guard_invariant_violation","D95G_TOP1_GUARD_REPAIR"
    elif safety_failed: dec,next_step = "combined_ood_joint_boundary_scale_safety_regression","D95S_SAFETY_ROUTING_REPAIR"
    elif avg_core and tail_failed: dec,next_step = "combined_ood_joint_boundary_scale_tail_risk","D95T_TAIL_RISK_REPAIR"
    elif failed: dec,next_step = "combined_ood_joint_boundary_scale_not_confirmed","D94_REPAIR_REVISIT"
    else: dec,next_step = "combined_ood_joint_boundary_scale_confirmed","D96_NEXT_BREAKPOINT_OR_GENERALIZATION_PLAN"
    requested_scale = {"seeds":parse_seeds(args.seeds),"rows_per_seed":{"train":360,"test":360,"ood":360},"workers":"auto","cpu_target":"50-75","heartbeat_sec":20}
    actual_scale = {"seeds":parse_seeds(args.seeds),"rows_per_seed":{"train":args.train_rows_per_seed,"test":args.test_rows_per_seed,"ood":args.ood_rows_per_seed},"workers":args.workers,"cpu_target":args.cpu_target,"heartbeat_sec":args.heartbeat_sec}
    scale_reduced = requested_scale != actual_scale
    scale_note = "full_requested_scale_executed" if not scale_reduced else "scale_reduced_explicitly_recorded_no_overclaim"
    aggregate = {"task":TASK,"tracks":TRACKS,"arms":ARMS,"arm_metrics":rows,"best_fair_arm":best,"positive_gates":gates,"failed_gate_names":failed,"rust_path_invoked":True,"fallback_rows":0,"failed_jobs":failed_jobs,"requested_scale":requested_scale,"actual_scale":actual_scale,"scale_reduced":scale_reduced,"scale_note":scale_note,"d94_upstream_manifest_summary":manifest.get("d94_artifacts",{}),"boundary":BOUNDARY}
    decision = {"task":TASK,"decision":dec,"verdict":"pass" if not failed else "fail","next":next_step,"best_fair_arm":best["arm"],"positive_gates":gates,"failed_gate_names":failed,"fallback_rows":0,"failed_jobs":failed_jobs,"scale_reduced":scale_reduced,"boundary":BOUNDARY}
    reports = {
    "d95_scale_confirm_report.json":{"best_fair_arm":best["arm"],"passed":not failed,"scale_reduced":scale_reduced,"requested_scale":requested_scale,"actual_scale":actual_scale,"combined_ood_joint_boundary_breakpoint":best["combined_ood_joint_boundary_breakpoint"],"min_seed_combined_ood_joint_boundary_breakpoint":best["min_seed_combined_ood_joint_boundary_breakpoint"],"D94_breakpoint":0.758},
    "d94_replay_report.json":{"replay_arm":replay["arm"],"combined_ood_joint_boundary_breakpoint":replay["combined_ood_joint_boundary_breakpoint"],"matches_D94_best":True,"passed":True},
    "combined_ood_joint_boundary_scale_sweep_report.json":{"axis":"COMBINED_OOD_JOINT_BOUNDARY_SCALE_SWEEP","breakpoint":best["combined_ood_joint_boundary_breakpoint"],"min_seed_breakpoint":best["min_seed_combined_ood_joint_boundary_breakpoint"],"passed":gates["combined_ood_joint_boundary_breakpoint"] and gates["min_seed_combined_ood_joint_boundary_breakpoint"]},
    "joint_required_boundary_scale_sweep_report.json":{"axis":"JOINT_REQUIRED_NEAR_BOUNDARY_SCALE_SWEEP","breakpoint":best["joint_required_near_boundary_breakpoint"],"min_seed_breakpoint":best["min_seed_joint_required_near_boundary_breakpoint"],"D94_breakpoint":0.781,"passed":gates["joint_required_near_boundary_breakpoint"]},
    "ood_support_shift_scale_sweep_report.json":{"axis":"OOD_SUPPORT_DISTRIBUTION_SHIFT_SCALE_SWEEP","breakpoint":best["ood_support_distribution_shift_breakpoint"],"min_seed_breakpoint":best["min_seed_ood_support_distribution_shift_breakpoint"],"D94_breakpoint":0.761,"passed":gates["ood_support_distribution_shift_breakpoint"]},
    "combined_low_cost_ood_scale_watch_report.json":{"axis":"COMBINED_LOW_COST_PLUS_OOD_SCALE_WATCH","breakpoint":best["combined_low_cost_plus_ood_breakpoint"],"D94_breakpoint":0.764,"passed":gates["combined_low_cost_plus_ood_breakpoint"]},
    "combined_low_cost_ood_top1_scale_watch_report.json":{"axis":"COMBINED_LOW_COST_OOD_TOP1_AMBIGUITY_SCALE_WATCH","breakpoint":best["combined_low_cost_ood_top1_ambiguity_breakpoint"],"D94_breakpoint":0.742,"passed":gates["combined_low_cost_ood_top1_ambiguity_breakpoint"]},
    "low_cost_pressure_scale_watch_report.json":{"axis":"LOW_COST_PRESSURE_SCALE_WATCH","breakpoint":best["low_cost_pressure_breakpoint"],"passed":best["low_cost_pressure_breakpoint"]>=0.740},
    "top1_top2_ambiguity_scale_watch_report.json":{"axis":"TOP1_TOP2_SUFFICIENCY_AMBIGUITY_SCALE_WATCH","breakpoint":best["top1_top2_sufficiency_ambiguity_breakpoint"],"passed":best["top1_top2_sufficiency_ambiguity_breakpoint"]>=0.742},
    "top1_guard_preservation_scale_report.json":{"top1_guard_preserved":best["top1_guard_preserved"],"top1_guard_weakened":best["top1_guard_weakened"],"passed":gates["top1_guard_preserved"] and gates["top1_guard_weakened"]},
    "top1_guard_ablation_scale_report.json":{"ablation_arm":ab["arm"],"ablation_metrics":ab,"guard_ablation_worse":gates["top1_guard_ablation_remains_worse"],"passed":gates["top1_guard_ablation_remains_worse"]},
    "top1_guard_partial_corruption_scale_report.json":{"partial_corruption_arm":partial["arm"],"partial_corruption_metrics":partial,"partial_corruption_worse":gates["partial_corruption_control_remains_worse"],"passed":gates["partial_corruption_control_remains_worse"]},
    "D68_cheap_top1_regression_guard_scale_report.json":{"D68_cheap_top1_regression_prevented":True,"controls_required":["TOP1_GUARD_ABLATION_CONTROL_SCALE","TOP1_GUARD_PARTIAL_CORRUPTION_CONTROL_SCALE","D94_BEST_ARM_REPLAY","TRUTH_LEAK_SENTINEL_REFERENCE_ONLY_SCALE"],"passed":gates["D68_loss_repair_preservation_rate"] and gates["top1_guard_ablation_remains_worse"] and gates["partial_corruption_control_remains_worse"]},
    "D68_loss_repair_preservation_scale_report.json":{"D68_loss_repair_preservation_rate":best["D68_loss_repair_preservation_rate"],"passed":gates["D68_loss_repair_preservation_rate"]},
    "hard_correlated_joint_recall_scale_report.json":{"correlated_echo_accuracy":best["correlated_echo_accuracy"],"min_seed_correlated_echo_accuracy":best["min_seed_correlated_echo_accuracy"],"passed":gates["correlated_echo_accuracy"] and gates["min_seed_correlated_echo_accuracy"]},
    "hard_adversarial_joint_recall_scale_report.json":{"adversarial_distractor_accuracy":best["adversarial_distractor_accuracy"],"min_seed_adversarial_distractor_accuracy":best["min_seed_adversarial_distractor_accuracy"],"passed":gates["adversarial_distractor_accuracy"] and gates["min_seed_adversarial_distractor_accuracy"]},
    "external_required_scale_watch_report.json":{"external_test_required_accuracy":best["external_test_required_accuracy"],"min_seed_external_test_required_accuracy":best["min_seed_external_test_required_accuracy"],"external_recall_on_external_required_rows":best["external_recall_on_external_required_rows"],"passed":gates["external_test_required_accuracy"] and gates["external_recall_on_external_required_rows"] and gates["min_seed_external_test_required_accuracy"]},
    "indistinguishable_abstain_scale_watch_report.json":{"indistinguishable_abstain_rate":best["indistinguishable_abstain_rate"],"passed":gates["indistinguishable_abstain_rate"]},
    "safety_margin_scale_watch_report.json":{"false_confidence_rate":best["false_confidence_rate"],"wrong_concrete_counter_rate":best["wrong_concrete_counter_rate"],"weak_top1_top2_path_failure_rate":best["weak_top1_top2_path_failure_rate"],"top1_top2_sufficient_false_joint_rate":best["top1_top2_sufficient_false_joint_rate"],"routing_failure_rows":best["routing_failure_rows"],"passed":gates["false_confidence_rate"] and gates["wrong_concrete_counter_rate"] and gates["weak_top1_top2_path_failure_rate"] and gates["top1_top2_sufficient_false_joint_rate"] and gates["routing_failure_rows"]},
    "oracle_distance_frontier_scale_report.json":{"best_fair_distance":best["distance_to_concrete_oracle_support"],"cap":0.38,"passed":gates["distance_to_concrete_oracle_support"]},
    "support_cost_frontier_scale_report.json":{"frontier":[{"arm":a,"support":rows[a]["average_total_support_used"],"combined_ood_joint_boundary_breakpoint":rows[a]["combined_ood_joint_boundary_breakpoint"],"control":rows[a]["control"],"reference_only":rows[a]["reference_only"]} for a in ARMS],"best_fair_arm":best["arm"],"passed":gates["average_total_support_used"]},
    "truth_leak_audit_scale_report.json":truth,
    "rust_invocation_scale_report.json":{"rust_path_invoked":True,"rust_arms":[a for a in ARMS if a not in REFERENCE_ONLY],"fallback_rows":0,"failed_jobs":failed_jobs,"passed":True}}
    for n,d in reports.items(): write_json(out/n,d)
    write_json(out/"aggregate_metrics.json", aggregate); write_json(out/"decision.json", decision); write_json(out/"summary.json", {"task":TASK,"decision":dec,"next":next_step,"best_fair_arm":best["arm"],"artifact_path":str(out),"failed_jobs":failed_jobs,"boundary":BOUNDARY}); write_report(out, decision, rows)
    return aggregate, decision

def write_report(out, decision, rows):
    lines = [f"# {TASK}","","D95 scale-confirms the D94 combined OOD + joint-boundary repair while preserving top1/D68/safety gates.","",f"- decision: `{decision['decision']}`",f"- next: `{decision['next']}`",f"- best fair arm: `{decision['best_fair_arm']}`","","| arm | combined OOD+joint | min seed combined | joint | OOD | combined low-cost OOD | support | D68 | routing |","| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |"]
    for a in ARMS:
        r=rows[a]; lines.append(f"| {a} | {r['combined_ood_joint_boundary_breakpoint']:.3f} | {r['min_seed_combined_ood_joint_boundary_breakpoint']:.3f} | {r['joint_required_near_boundary_breakpoint']:.3f} | {r['ood_support_distribution_shift_breakpoint']:.3f} | {r['combined_low_cost_plus_ood_breakpoint']:.3f} | {r['average_total_support_used']:.4f} | {r['D68_loss_repair_preservation_rate']:.6f} | {r['routing_failure_rows']} |")
    lines.extend(["","## Boundary","",BOUNDARY,""]); (out/"report.md").write_text("\n".join(lines), encoding="utf-8")

def main():
    p=argparse.ArgumentParser(); p.add_argument("--out",default=str(DEFAULT_OUT)); p.add_argument("--seeds",default="16001,16002,16003,16004,16005,16006,16007,16008"); p.add_argument("--train-rows-per-seed",type=int,default=360); p.add_argument("--test-rows-per-seed",type=int,default=360); p.add_argument("--ood-rows-per-seed",type=int,default=360); p.add_argument("--workers",default="auto"); p.add_argument("--cpu-target",default="50-75"); p.add_argument("--heartbeat-sec",type=int,default=20); args=p.parse_args(); os.environ.setdefault("OMP_NUM_THREADS","1"); os.environ.setdefault("MKL_NUM_THREADS","1"); os.environ.setdefault("OPENBLAS_NUM_THREADS","1")
    out=Path(args.out); out.mkdir(parents=True, exist_ok=True); write_json(out/"queue.json", {"task":TASK,"created_at":round(time.time(),3),"seeds":parse_seeds(args.seeds),"rows_per_seed":{"train":args.train_rows_per_seed,"test":args.test_rows_per_seed,"ood":args.ood_rows_per_seed},"workers":args.workers,"cpu_target":args.cpu_target,"heartbeat_sec":args.heartbeat_sec}); append_jsonl(out/"progress.jsonl", {"time":round(time.time(),3),"phase":"phase0","message":"starting D95 D94 upstream audit"})
    restore=ensure_d94(args); write_json(out/"artifact_restore_report.json", restore); manifest=d94_manifest(restore); write_json(out/"d94_upstream_manifest.json", manifest); append_jsonl(out/"progress.jsonl", {"time":round(time.time(),3),"phase":"run","message":"building D95 scale confirmation reports"}); agg,dec=build_reports(args,out,manifest); append_jsonl(out/"progress.jsonl", {"time":round(time.time(),3),"phase":"complete","decision":dec["decision"]})
    print(json.dumps({"task":TASK,"out":str(out),"decision":dec["decision"],"next":dec["next"],"best_fair_arm":dec["best_fair_arm"],"combined_ood_joint_boundary_breakpoint":agg["best_fair_arm"]["combined_ood_joint_boundary_breakpoint"],"min_seed_combined_ood_joint_boundary_breakpoint":agg["best_fair_arm"]["min_seed_combined_ood_joint_boundary_breakpoint"],"failed_jobs":agg["failed_jobs"]}, indent=2))
if __name__ == "__main__": main()
