#!/usr/bin/env python3
"""Validate D103 sparse recurrent microcircuit scale artifacts."""
from __future__ import annotations
import argparse, json, sys
from pathlib import Path
TASK="D103_SPARSE_RECURRENT_MICROCIRCUIT_SCALE_CONFIRM"; D102_COMMIT="1765ae8562fb1b806f02264c1ea6451ab97247d0"
REPORTS="""d102_upstream_manifest.json d103_scale_report.json d103_dense_baseline_preservation_report.json d103_sparse_candidate_scale_eval_report.json d103_sparse_checkpoint_replay_report.json d103_sparse_mask_replay_report.json d103_sparse_mask_stability_report.json d103_sparse_mask_permutation_report.json d103_sparse_mask_jitter_report.json d103_sparse_recovery_report.json d103_protected_component_integrity_report.json d103_candidate_component_targeting_report.json d103_sparse_route_distribution_report.json d103_sparse_loop_utility_report.json d103_sparse_convergence_report.json d103_sparse_halting_report.json d103_sparse_state_robustness_report.json d103_low_cost_ood_top1_ambiguity_tail_sparse_report.json d103_combined_ood_joint_boundary_carryover_report.json d103_ood_stress_scale_carryover_report.json d103_min_seed_worst_seed_sparse_report.json d103_safety_margin_sparse_report.json d103_top1_guard_sparse_report.json d103_D68_sparse_report.json d103_oracle_distance_frontier_sparse_report.json d103_support_cost_frontier_sparse_report.json d103_compression_efficiency_report.json d103_sparse_inference_cost_report.json d103_rust_sparse_invocation_report.json d103_reference_only_oversparsity_report.json d103_reference_only_pressure_report.json d103_control_mask_report.json d103_label_shuffle_sentinel_report.json d103_regime_label_leak_sentinel_report.json d103_row_id_lookup_sentinel_report.json d103_python_hash_lookup_sentinel_report.json d103_file_order_artifact_sentinel_report.json d103_seed_id_shortcut_sentinel_report.json d103_hidden_state_label_leak_sentinel_report.json d103_hidden_state_row_lookup_sentinel_report.json d103_halt_step_shortcut_sentinel_report.json d103_step_count_shortcut_sentinel_report.json d103_mask_id_shortcut_sentinel_report.json d103_sparsity_pattern_shortcut_sentinel_report.json d103_checkpoint_id_shortcut_sentinel_report.json d103_component_id_shortcut_sentinel_report.json d103_sparse_mask_replay_shortcut_sentinel_report.json d103_sparse_rust_path_shortcut_sentinel_report.json d103_split_integrity_report.json d103_overfit_memorization_report.json d103_negative_controls_report.json d103_truth_leak_oracle_isolation_report.json d103_report_schema_metric_crosscheck_report.json d103_deterministic_replay_report.json aggregate_metrics.json decision.json summary.json report.md""".split()
def load(p:Path): return json.loads(p.read_text(encoding="utf-8"))
def expect(cond,msg):
    if not cond: raise SystemExit(f"D103 check failed: {msg}")
def main():
    ap=argparse.ArgumentParser(); ap.add_argument("--out",type=Path,default=Path("target/pilot_wave/d103_sparse_recurrent_microcircuit_scale_confirm")); args=ap.parse_args(); out=args.out
    missing=[r for r in REPORTS if not (out/r).exists()]; expect(not missing,f"missing reports: {missing}")
    agg=load(out/"aggregate_metrics.json"); dec=load(out/"decision.json"); summ=load(out/"summary.json"); man=load(out/"d102_upstream_manifest.json"); m=agg["metrics"]; g=agg["positive_gates"]
    expect(agg["task"]==TASK,"task mismatch"); expect(man["requested_d102_commit"]==D102_COMMIT,"D102 commit mismatch")
    expect(man["artifact_present"] and man["validation_status"]=="passed","D102 handoff invalid"); expect(man["replayed_decision"]=="d102_controlled_sparse_auto_anneal_prototype_confirmed","D102 decision mismatch"); expect(man["replayed_next"]==TASK,"D102 next mismatch"); expect(man["replayed_d103_ready"] is True,"D102 d103_ready mismatch"); expect(man["replayed_final_sparse_candidate"]=="D102_SPARSE_AUTO_ANNEAL_8PCT_LIGHT_PROTECTED_FAIR" and man["replayed_final_sparse_pct"]==8 and man["replayed_final_anneal_pressure"]=="light","D102 sparse candidate mismatch")
    if not man.get("commit_present"): expect(man.get("restore_or_rerun_attempted") and man.get("restore_or_rerun_succeeded"),"missing D102 commit requires restore/rerun")
    expect(dec["decision"]=="d103_sparse_recurrent_microcircuit_scale_confirmed","unexpected decision"); expect(dec["next"]=="D104_SPARSE_RECURRENT_GENERALIZATION_AND_COMPRESSION_FRONTIER_MAP","unexpected next"); expect(dec["d104_ready"] is True,"d104_ready mismatch")
    expect(dec["final_sparse_pct"]==8 and dec["final_anneal_pressure"]=="light" and dec["final_sparse_candidate_name"]=="D102_SPARSE_AUTO_ANNEAL_8PCT_LIGHT_PROTECTED_FAIR","final sparse identity mismatch")
    expect(dec["failed_jobs"]==[] and dec["fallback_rows"]==0 and dec["scale_reduced"] is False,"failed/fallback/scale issue"); expect(agg["scale"]["scale_reduced"] is False and agg["scale"]["all_required_stress_modes_executed"],"scale issue"); expect(all(g.values()),f"positive gates failed: {[k for k,v in g.items() if not v]}")
    for r in REPORTS:
        if r in {"d102_upstream_manifest.json","aggregate_metrics.json","decision.json","summary.json","report.md"}: continue
        expect(load(out/r).get("passed") is True,f"{r} not passed")
    expect(m["dense_baseline_preserved"] and m["sparse_candidate_replayed"] and m["sparse_candidate_scale_confirmed"],"sparse candidate replay failure")
    expect(m["final_sparse_pct"]==8 and m["final_anneal_pressure"]=="light","sparse identity gate failure")
    expect(m["protected_components_locked"] and m["protected_component_modification_count"]==0,"protected component violation")
    expect(m["candidate_components_targeted"] and m["candidate_component_modification_count"]>0,"candidate targeting failure")
    expect(m["checkpoint_replay_passed"] and m["checkpoint_replay_match_rate"]>=0.999 and m["sparse_mask_replay_passed"] and m["sparse_mask_replay_match_rate"]>=0.999 and m["sparse_mask_stability_score"]>=0.95 and m["sparse_recovery_rate"]>=0.995,"checkpoint/mask replay failure")
    for k,t in {"sparse_scale_test_accuracy":0.9940,"sparse_scale_ood_accuracy":0.9915,"sparse_scale_stress_accuracy":0.9910,"sparse_scale_min_seed_accuracy":0.9905,"sparse_scale_worst_seed_accuracy":0.9895,"sparse_scale_convergence_rate":0.998,"sparse_scale_loop_usefulness_score":0.70,"sparse_scale_loop_usefulness_on_tail_score":0.70,"sparse_scale_state_stability_score":0.80,"sparse_scale_low_cost_ood_top1_tail_score":0.746,"sparse_scale_min_seed_low_cost_ood_top1_tail_score":0.742,"sparse_scale_combined_ood_joint_boundary_breakpoint":0.755,"sparse_scale_min_seed_combined_ood_joint_boundary_breakpoint":0.752,"sparse_scale_external_required_accuracy":0.995,"sparse_scale_joint_required_accuracy":0.994,"sparse_scale_indistinguishable_abstain_rate":0.9948,"sparse_scale_inference_cost_reduction_pct":6.0,"sparse_scale_active_component_reduction_pct":8.0}.items(): expect(m[k]>=t,f"{k} below threshold")
    for k,c in {"sparse_scale_overfit_gap":0.015,"sparse_scale_false_confidence_rate":0.0046,"sparse_scale_non_convergence_rate":0.001,"sparse_scale_oscillation_rate":0.001,"sparse_scale_halting_false_positive_rate":0.0046,"sparse_scale_wrong_concrete_counter_rate":0.0007,"sparse_scale_weak_top1_top2_path_failure_rate":0.0006,"sparse_scale_top1_top2_sufficient_false_joint_rate":0.0015,"sparse_scale_worst_tail_failure_rate":0.003,"sparse_scale_mixed_tail_compound_failure_rate":0.004,"sparse_scale_false_positive_confidence_tail_rate":0.0048,"sparse_scale_distance_to_symbolic_teacher":0.025,"sparse_scale_distance_to_d100_recurrent":0.025,"sparse_scale_distance_to_d101_baseline":0.025,"sparse_scale_distance_to_d102_sparse":0.025,"sparse_scale_distance_to_concrete_oracle_support":0.385,"sparse_scale_average_support_used":6.75,"sparse_scale_average_steps_used":5.0,"sparse_scale_max_steps_used":8,"memorization_risk_score":0.10}.items(): expect(m[k]<=c,f"{k} above ceiling")
    expect(m["sparse_scale_routing_failure_rows"]==0 and m["sparse_scale_D68_preservation_rate"]==1.0 and m["sparse_scale_top1_guard_preserved"] and not m["sparse_scale_top1_guard_weakened"],"sparse guard failure")
    expect(m["sparse_scale_rust_path_invoked"] and m["sparse_scale_fallback_rows"]==0 and m["sparse_scale_failed_jobs"]==[] and m["rust_path_invoked"] and m["fallback_rows"]==0 and m["failed_jobs"]==[],"rust/fallback failure")
    for key in ["label_shuffle_sentinel_accuracy","regime_label_leak_sentinel_accuracy","row_id_lookup_sentinel_accuracy","python_hash_lookup_sentinel_accuracy","file_order_artifact_sentinel_accuracy","seed_id_shortcut_sentinel_accuracy","hidden_state_label_leak_sentinel_accuracy","hidden_state_row_lookup_sentinel_accuracy","halt_step_shortcut_sentinel_accuracy","step_count_shortcut_sentinel_accuracy","mask_id_shortcut_sentinel_accuracy","sparsity_pattern_shortcut_sentinel_accuracy","checkpoint_id_shortcut_sentinel_accuracy","component_id_shortcut_sentinel_accuracy","sparse_mask_replay_shortcut_sentinel_accuracy","sparse_rust_path_shortcut_sentinel_accuracy"]: expect(m[key]<=0.56,f"{key} shortcut too high")
    expect(not m["forbidden_feature_detected"] and not m["route_distillation_label_leak_risk"] and m["split_integrity_passed"] and not m["train_test_ood_contamination_detected"] and m["sentinel_collapse_passed"],"leak/split/sentinel failure")
    expect(m["deterministic_replay_passed"] and m["report_schema_consistency_passed"] and m["metric_crosscheck_passed"],"infrastructure failure"); expect(summ["decision"]==dec["decision"] and summ["next"]==dec["next"],"summary mismatch")
    print(json.dumps({"status":"passed","artifact_path":str(out),"decision":dec["decision"],"next":dec["next"],"final_sparse_pct":dec["final_sparse_pct"]},indent=2,sort_keys=True))
if __name__=="__main__": main()
