#!/usr/bin/env python3
"""Validate D97 mechanism feature audit and surrogate training prototype artifacts."""
from __future__ import annotations
import argparse, json, sys
from pathlib import Path
REPORTS=["d96_upstream_manifest.json","d97_feature_schema_report.json","d97_forbidden_feature_audit_report.json","d97_route_distillation_target_report.json","d97_split_integrity_report.json","d97_low_cost_ood_top1_ambiguity_tail_report.json","d97_surrogate_training_report.json","d97_surrogate_linear_probe_report.json","d97_surrogate_small_mlp_report.json","d97_surrogate_rule_distillation_report.json","d97_surrogate_calibrated_threshold_report.json","d97_surrogate_ensemble_reference_report.json","d97_surrogate_ood_eval_report.json","d97_surrogate_stress_tail_eval_report.json","d97_surrogate_min_seed_eval_report.json","d97_surrogate_top1_guard_report.json","d97_surrogate_D68_guard_report.json","d97_surrogate_safety_margin_report.json","d97_surrogate_oracle_distance_frontier_report.json","d97_surrogate_support_cost_frontier_report.json","d97_label_shuffle_sentinel_report.json","d97_regime_label_leak_sentinel_report.json","d97_row_id_lookup_sentinel_report.json","d97_python_hash_lookup_sentinel_report.json","d97_feature_ablation_report.json","d97_feature_importance_stability_report.json","d97_overfit_memorization_audit_report.json","d97_top1_guard_ablation_control_report.json","d97_top1_guard_partial_corruption_control_report.json","d97_negative_controls_report.json","d97_truth_leak_oracle_isolation_report.json","d97_rust_invocation_report.json","d97_report_schema_metric_crosscheck_report.json","aggregate_metrics.json","decision.json","summary.json","report.md"]
ALLOWED={"d97_surrogate_training_prototype_confirmed","d97_surrogate_tail_risk_detected","d97_surrogate_safety_regression","d97_forbidden_feature_or_label_leak_detected","d97_shortcut_memorization_detected","d97_split_contamination_detected","d97_surrogate_training_not_confirmed","d96_preservation_regression_detected","top1_guard_invariant_violation","d68_regression_detected","d97_invalid_metric_or_report_inconsistency","d97_invalid_or_incomplete_run"}
def load(p:Path): return json.loads(p.read_text(encoding="utf-8"))
def fail(m): print(f"D97 check failed: {m}",file=sys.stderr); sys.exit(1)
def main():
    p=argparse.ArgumentParser(); p.add_argument("--out",default="target/pilot_wave/d97_mechanism_feature_audit_and_surrogate_training_prototype"); args=p.parse_args(); out=Path(args.out)
    missing=[r for r in REPORTS if not (out/r).exists()]
    if missing: fail(f"missing reports {missing}")
    man=load(out/"d96_upstream_manifest.json"); agg=load(out/"aggregate_metrics.json"); dec=load(out/"decision.json"); summ=load(out/"summary.json"); m=agg.get("metrics",{})
    if dec.get("decision") not in ALLOWED: fail(f"bad decision {dec.get('decision')}")
    if dec.get("decision")!="d97_surrogate_training_prototype_confirmed": fail(f"unexpected decision {dec.get('decision')}")
    if dec.get("next")!="D98_SURROGATE_ADVERSARIAL_SCALE_CONFIRM": fail(f"unexpected next {dec.get('next')}")
    if dec.get("failed_jobs") or agg.get("failed_jobs") or m.get("failed_jobs"): fail("failed_jobs present")
    if dec.get("fallback_rows")!=0 or agg.get("fallback_rows")!=0 or m.get("fallback_rows")!=0: fail("fallback rows nonzero")
    d96=man.get("d96_artifacts",{})
    if man.get("requested_d96_commit")!="d05dd767224ce75ef8b647f3db0480a55efced7e": fail("requested D96 commit mismatch")
    if not man.get("commit_present") and not (man.get("restore_or_rerun_attempted") and man.get("restore_or_rerun_succeeded")): fail("D96 commit missing without successful restore/rerun")
    if not man.get("artifact_present") or man.get("validation_status")!="passed": fail("D96 artifact/validation failed")
    if d96.get("decision")!="d96_breakpoint_map_complete_train_loop_bridge_ready" or d96.get("next")!="D97_MECHANISM_FEATURE_AUDIT_AND_SURROGATE_TRAINING_PROTOTYPE": fail("D96 handoff mismatch")
    if d96.get("next_breakpoint_name")!="COMBINED_LOW_COST_OOD_TOP1_AMBIGUITY_TAIL" or d96.get("trainable_surrogate_ready") is not True: fail("D96 bridge mismatch")
    gates=agg.get("positive_gates",{}); failed=[k for k,v in gates.items() if not v]
    if failed: fail(f"positive gates failed {failed}")
    for r in REPORTS:
        if r.endswith(".json") and r not in {"aggregate_metrics.json","decision.json","summary.json","d96_upstream_manifest.json"} and not load(out/r).get("passed",True): fail(f"{r} did not pass")
    if m.get("surrogate_best_fair_arm")!="SURROGATE_SMALL_MLP_FAIR": fail("unexpected best fair surrogate")
    checks={"surrogate_best_fair_accuracy":m.get("surrogate_best_fair_accuracy",0)>=0.993,"surrogate_best_fair_train_accuracy":m.get("surrogate_best_fair_train_accuracy",0)>=0.993,"surrogate_best_fair_test_accuracy":m.get("surrogate_best_fair_test_accuracy",0)>=0.993,"surrogate_best_fair_min_seed_accuracy":m.get("surrogate_best_fair_min_seed_accuracy",0)>=0.990,"surrogate_best_fair_ood_accuracy":m.get("surrogate_best_fair_ood_accuracy",0)>=0.991,"surrogate_best_fair_stress_accuracy":m.get("surrogate_best_fair_stress_accuracy",0)>=0.990,"overfit":m.get("surrogate_best_fair_overfit_gap",1)<=0.015,"false_conf":m.get("surrogate_best_fair_false_confidence_rate",1)<=0.0046,"routing":m.get("surrogate_best_fair_routing_failure_rows")==0,"D68":m.get("surrogate_best_fair_D68_preservation_rate")==1.0,"top1":m.get("surrogate_best_fair_top1_guard_preserved") is True and m.get("surrogate_best_fair_top1_guard_weakened") is False,"truth":m.get("surrogate_best_fair_truth_leak_audit_passed") is True,"oracle":m.get("surrogate_best_fair_oracle_isolation_passed") is True,"teacher_distance":m.get("surrogate_best_fair_distance_to_symbolic_teacher",1)<=0.025,"oracle_distance":m.get("surrogate_best_fair_distance_to_concrete_oracle_support",1)<=0.385,"support":m.get("surrogate_best_fair_average_support_used",99)<=6.75,"tail":m.get("surrogate_best_fair_low_cost_ood_top1_ambiguity_tail_score",0)>=0.742,"min_tail":m.get("surrogate_best_fair_min_seed_low_cost_ood_top1_ambiguity_tail_score",0)>=0.739,"combined":m.get("surrogate_best_fair_combined_ood_joint_boundary_breakpoint",0)>=0.755,"min_combined":m.get("surrogate_best_fair_min_seed_combined_ood_joint_boundary_breakpoint",0)>=0.752,"external":m.get("surrogate_best_fair_external_required_accuracy",0)>=0.995,"joint":m.get("surrogate_best_fair_joint_required_accuracy",0)>=0.994,"abstain":m.get("surrogate_best_fair_indistinguishable_abstain_rate",0)>=0.9948,"wrong":m.get("surrogate_best_fair_wrong_concrete_counter_rate",1)<=0.0007,"weak":m.get("surrogate_best_fair_weak_top1_top2_path_failure_rate",1)<=0.0006,"false_joint":m.get("surrogate_best_fair_top1_top2_sufficient_false_joint_rate",1)<=0.0015,"sentinel":m.get("sentinel_collapse_passed") is True,"memorization":m.get("memorization_risk_score",1)<=0.10,"feature_stability":m.get("feature_importance_stability",0)>=0.70,"rust":m.get("rust_path_invoked") is True,"fallback":m.get("fallback_rows")==0,"failed_jobs":m.get("failed_jobs")==[]}
    bad=[k for k,v in checks.items() if not v]
    if bad: fail(f"metric gates failed {bad}")
    if m.get("forbidden_feature_detected") or m.get("forbidden_feature_names") or m.get("route_distillation_label_leak_risk") or not m.get("split_integrity_passed") or m.get("train_test_ood_contamination_detected"): fail("feature/distillation/split audit failed")
    if m.get("label_shuffle_sentinel_accuracy",1)>0.55 or m.get("regime_label_leak_sentinel_accuracy",1)>0.56 or m.get("row_id_lookup_sentinel_accuracy",1)>0.55 or m.get("python_hash_lookup_sentinel_accuracy",1)>0.55: fail("sentinel shortcut failed")
    if summ.get("decision")!=dec.get("decision") or summ.get("next")!=dec.get("next") or summ.get("surrogate_best_fair_arm")!=m.get("surrogate_best_fair_arm"): fail("summary mismatch")
    print(json.dumps({"check":"passed","out":str(out),"decision":dec,"surrogate_best_fair_arm":m.get("surrogate_best_fair_arm"),"surrogate_best_fair_accuracy":m.get("surrogate_best_fair_accuracy"),"failed_jobs":m.get("failed_jobs")},indent=2))
if __name__=="__main__": main()
