"""
Export trained Python network to C arrays
==========================================
Reads a checkpoint (.npz) and outputs instnct_data.c
with neuron properties, edge list, and SDR table.

Usage: python export_network.py <checkpoint.npz> > instnct_data.c
"""
import sys, os, numpy as np
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'model'))
from graph import SelfWiringGraph

def build_sdr_table(in_dim, sdr_k, seed=42):
    rng = np.random.RandomState(seed)
    table = np.zeros((256, sdr_k), dtype=np.uint16)
    for v in range(256):
        table[v] = rng.choice(in_dim, size=sdr_k, replace=False).astype(np.uint16)
    return table

if __name__ == "__main__":
    if len(sys.argv) < 2:
        # Use default checkpoint path
        ckpt_path = os.path.join(os.path.dirname(__file__), '..', 'recipes', 'data', 'big_relu_main_network.npz')
    else:
        ckpt_path = sys.argv[1]

    if not os.path.exists(ckpt_path):
        print(f"/* ERROR: checkpoint not found: {ckpt_path} */", file=sys.stderr)
        print(f"/* Using dummy data for compilation test */")
        H = 256
        mask = (np.random.RandomState(42).rand(H,H) < 0.05).astype(bool)
        np.fill_diagonal(mask, False)
        theta = np.full(H, 6, dtype=np.uint8)
        channel = np.random.RandomState(42).randint(1, 9, size=H).astype(np.uint8)
        polarity = np.random.RandomState(42).rand(H) > 0.1
        pol_f32 = np.where(polarity, 1.0, -1.0).astype(np.float32)
        refr_period = np.ones(H, dtype=np.uint8)
    else:
        ckpt = np.load(ckpt_path)
        mask = ckpt['mask']
        H = mask.shape[0]
        theta = ckpt['theta'].astype(np.uint8) if 'theta' in ckpt.files else np.full(H, 6, np.uint8)
        channel = ckpt['channel'] if 'channel' in ckpt.files else np.ones(H, np.uint8)
        pol_f32 = ckpt['pol_f32'] if 'pol_f32' in ckpt.files else np.ones(H, np.float32)
        polarity = (pol_f32 > 0)
        refr_period = ckpt['refr_period'] if 'refr_period' in ckpt.files else np.ones(H, np.uint8)

    PHI = (1 + 5**0.5) / 2
    IN_DIM = int(round(H / PHI))
    SDR_K = int(round(IN_DIM * 0.20))

    rows, cols = np.where(mask)
    n_edges = len(rows)

    sdr_table = build_sdr_table(IN_DIM, SDR_K)

    print("/* Auto-generated by export_network.py — DO NOT EDIT */")
    print(f'#include "instnct_edge.h"')
    print()

    # Neurons
    print(f"const InstnctNeuron instnct_neurons[{H}] = {{")
    for i in range(H):
        th = int(np.clip(theta[i], 1, 15))
        ch = int(np.clip(channel[i], 1, 8))
        pol = 1 if polarity[i] else 0
        rp = int(np.clip(refr_period[i], 0, 15))
        comma = "," if i < H-1 else ""
        print(f"  {{{th:2d}, {ch}, {pol}, {rp:2d}}}{comma} /* neuron {i} */")
    print("};")
    print()

    # Edges
    print(f"const InstnctEdge instnct_edges[{n_edges}] = {{")
    for e in range(n_edges):
        comma = "," if e < n_edges-1 else ""
        print(f"  {{{int(rows[e]):3d}, {int(cols[e]):3d}}}{comma}")
    print("};")
    print(f"const int instnct_n_edges = {n_edges};")
    print()

    # SDR table
    print(f"const uint16_t INSTNCT_SDR_TABLE[256][{SDR_K}] = {{")
    for v in range(256):
        vals = ", ".join(f"{int(sdr_table[v,k]):3d}" for k in range(SDR_K))
        comma = "," if v < 255 else ""
        print(f"  {{{vals}}}{comma}")
    print("};")

    print(f"\n/* H={H} edges={n_edges} SDR_K={SDR_K} IN_DIM={IN_DIM} */")
