"""
Export trained ReLU controller weights to C int8 arrays
========================================================
Quantizes float32 weights to int8 (scale=64).
Usage: python export_controller.py [weights.npz] > instnct_ctrl_data.c
"""
import sys, os
import numpy as np

SCALE = 64  # int8 scale factor: 1.0 = 64

def quantize_int8(W, scale=SCALE):
    """Quantize float32 to int8 with scale factor."""
    q = np.clip(np.round(W * scale), -127, 127).astype(np.int8)
    return q

if __name__ == "__main__":
    if len(sys.argv) >= 2:
        ckpt_path = sys.argv[1]
    else:
        ckpt_path = os.path.join(os.path.dirname(__file__), '..', 'recipes', 'data', 'big_relu_ctrl_weights.npz')

    if os.path.exists(ckpt_path):
        w = np.load(ckpt_path)
        W1=w['W1'];b1=w['b1'];W2=w['W2'];b2=w['b2'];W3=w['W3'];b3=w['b3'];Wo=w['Wo'];bo=w['bo']
    else:
        print(f"/* WARNING: {ckpt_path} not found, using random init */", file=sys.stderr)
        rng = np.random.RandomState(99)
        h = 64
        W1=rng.randn(10,h).astype(np.float32)*0.4
        b1=np.zeros(h,np.float32)
        W2=rng.randn(h,h).astype(np.float32)*0.2
        b2=np.zeros(h,np.float32)
        W3=rng.randn(h,h).astype(np.float32)*0.2
        b3=np.zeros(h,np.float32)
        Wo=rng.randn(h,6).astype(np.float32)*0.1
        bo=np.zeros(6,np.float32)

    # Quantize
    qW1=quantize_int8(W1);qb1=quantize_int8(b1)
    qW2=quantize_int8(W2);qb2=quantize_int8(b2)
    qW3=quantize_int8(W3);qb3=quantize_int8(b3)
    qWo=quantize_int8(Wo);qbo=quantize_int8(bo)

    # Quantization error
    for name, orig, quant in [('W1',W1,qW1),('W2',W2,qW2),('W3',W3,qW3),('Wo',Wo,qWo)]:
        err = np.abs(orig - quant.astype(np.float32)/SCALE).mean()
        print(f"/* {name}: quant error = {err:.6f} */", file=sys.stderr)

    h = W1.shape[1]

    print("/* Auto-generated by export_controller.py — DO NOT EDIT */")
    print(f'#include "instnct_controller.h"')
    print()

    def print_2d(name, arr):
        rows, cols = arr.shape
        print(f"  .{name} = {{")
        for r in range(rows):
            vals = ", ".join(f"{int(arr[r,c]):4d}" for c in range(cols))
            comma = "," if r < rows-1 else ""
            print(f"    {{{vals}}}{comma}")
        print(f"  }},")

    def print_1d(name, arr):
        vals = ", ".join(f"{int(v):4d}" for v in arr)
        print(f"  .{name} = {{{vals}}},")

    print(f"const InstnctController instnct_controller = {{")
    print_2d("W1", qW1)
    print_1d("b1", qb1)
    print_2d("W2", qW2)
    print_1d("b2", qb2)
    print_2d("W3", qW3)
    print_1d("b3", qb3)
    print_2d("Wo", qWo)
    print_1d("bo", qbo)
    print(f"}};")
    print(f"\n/* hidden={h} scale={SCALE} total_bytes={qW1.nbytes+qb1.nbytes+qW2.nbytes+qb2.nbytes+qW3.nbytes+qb3.nbytes+qWo.nbytes+qbo.nbytes} */")
