"""
Generate EFF_THETA_LUT as C array
==================================
Precomputes theta × WAVE_LUT[channel][tick] for all combinations.
Output: instnct_lut.c with const uint8_t INSTNCT_EFF_THETA[16][9][8]
"""
import sys, os, numpy as np
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'model'))
from graph import SelfWiringGraph

WAVE_LUT = SelfWiringGraph.WAVE_LUT  # (9, 8)

print("/* Auto-generated by gen_lut.py — DO NOT EDIT */")
print('#include "instnct_edge.h"')
print()
print("const uint8_t INSTNCT_EFF_THETA[16][9][8] = {")

for th in range(16):
    print(f"  {{ /* theta={th} */")
    for ch in range(9):
        vals = []
        for t in range(8):
            if th == 0 or ch == 0:
                vals.append(1)  # unused, safe default
            else:
                v = max(1, min(15, round(th * WAVE_LUT[ch, t])))
                vals.append(int(v))
        line = ", ".join(f"{v:2d}" for v in vals)
        comma = "," if ch < 8 else ""
        print(f"    {{{line}}}{comma} /* ch={ch} */")
    comma = "," if th < 15 else ""
    print(f"  }}{comma}")

print("};")
