/*
 * INSTNCT Edge — Pure integer forward pass for microcontrollers
 * =============================================================
 * Zero float, zero sin(), connection-list-only propagation.
 * Runs on Arduino ($3), ESP32 ($4), RPi ($15).
 *
 * Learnable params: theta(int4), channel(int3), polarity(1bit), refractory(int4)
 * Fixed: decay(every 6th tick), WAVE_LUT(cos-shaped 9x8)
 *
 * Memory footprint (H=256):
 *   Neurons: 1 KB (4 byte/neuron struct)
 *   Edges: ~13 KB (4 byte/edge, ~3250 edges)
 *   ROM: ~9 KB (EFF_THETA_LUT + SDR_TABLE)
 *   Runtime: 768 byte (charge + spike + refr_counter)
 *   TOTAL: ~24 KB
 */

#ifndef INSTNCT_EDGE_H
#define INSTNCT_EDGE_H

#include <stdint.h>

/* Network dimensions — configurable at compile time */
#ifndef INSTNCT_H
#define INSTNCT_H 256
#endif

#define INSTNCT_TICKS 8
#define INSTNCT_INPUT_DURATION 2
#define INSTNCT_DECAY_PERIOD 6
#define INSTNCT_MAX_CHARGE 15
#define INSTNCT_SDR_K 32

/* Neuron properties */
typedef struct {
    uint8_t theta;       /* firing threshold [1-15] */
    uint8_t channel;     /* tick specialist [1-8] */
    uint8_t polarity;    /* 0=inhibitory(-1), 1=excitatory(+1) */
    uint8_t refr_period; /* refractory period [0-15] ticks */
} InstnctNeuron;

/* Sparse connection (edge) */
typedef struct {
    uint16_t source;
    uint16_t target;
} InstnctEdge;

/* Network state (persists between tokens) */
typedef struct {
    int8_t charge[INSTNCT_H];
    uint8_t refr_counter[INSTNCT_H];
} InstnctState;

/* Precomputed effective theta LUT: EFF_THETA[theta][channel][tick]
 * theta: 0-15 (0 unused), channel: 0-8 (0 unused), tick: 0-7
 * Values: uint8, range [1-20]
 * Generated by gen_lut.py */
extern const uint8_t INSTNCT_EFF_THETA[16][9][INSTNCT_TICKS];

/* SDR input table: SDR_TABLE[byte_value][k] = neuron index
 * 32 active neurons per byte value
 * Generated by export_network.py */
extern const uint16_t INSTNCT_SDR_TABLE[256][INSTNCT_SDR_K];

/*
 * Forward pass: process one token through the network.
 *
 * neurons:    array of H neuron properties (const, from flash)
 * edges:      sparse connection list (const, from flash)
 * n_edges:    number of connections
 * sdr_active: indices of active input neurons for this byte
 * n_active:   number of active inputs (typically SDR_K=32)
 * state:      network state (charge + refractory counters), persists between calls
 * spike_out:  output array — which neurons fired on the last tick
 */
void instnct_rollout_token(
    const InstnctNeuron neurons[],
    const InstnctEdge edges[],
    int n_edges,
    const uint16_t sdr_active[],
    int n_active,
    InstnctState *state,
    int8_t spike_out[]
);

/*
 * Readout: convert output zone charges to predicted byte.
 *
 * state:      current network state (reads charge from output zone)
 * out_proj:   output projection matrix (float, only place we need float)
 *             OR simplified: argmax of output zone charges
 * Returns:    predicted next byte [0-255]
 */
uint8_t instnct_readout_simple(const InstnctState *state);

/*
 * Reset network state (between sequences or on init).
 */
void instnct_state_reset(InstnctState *state);

#endif /* INSTNCT_EDGE_H */
