/*
 * INSTNCT Edge — Main loop (while-true byte processor)
 * For Arduino/ESP32/RPi: reads bytes from UART, predicts next byte.
 *
 * Compile: gcc -O2 -o instnct instnct_edge.c instnct_main.c instnct_data.c
 * Or for Arduino: include all .c files in sketch.
 */

#include "instnct_edge.h"
#include <stdio.h>

/* These are generated by export_network.py and gen_lut.py */
/* For now, placeholder externs — real data comes from instnct_data.c */

int main(void) {
    /* Network data (loaded from generated instnct_data.c) */
    extern const InstnctNeuron instnct_neurons[INSTNCT_H];
    extern const InstnctEdge instnct_edges[];
    extern const int instnct_n_edges;

    /* Runtime state */
    InstnctState state;
    int8_t spike[INSTNCT_H];
    instnct_state_reset(&state);

    printf("INSTNCT Edge ready. H=%d. Waiting for input...\n", INSTNCT_H);

    /* Main while-true loop */
    while (1) {
        int c = getchar();
        if (c == EOF) break;
        uint8_t byte_in = (uint8_t)c;

        /* SDR lookup */
        const uint16_t *sdr = INSTNCT_SDR_TABLE[byte_in];

        /* Forward pass: 8 ticks, pure integer */
        instnct_rollout_token(
            instnct_neurons,
            instnct_edges,
            instnct_n_edges,
            sdr,
            INSTNCT_SDR_K,
            &state,
            spike
        );

        /* Readout */
        uint8_t byte_out = instnct_readout_simple(&state);
        putchar(byte_out);
    }

    return 0;
}
