"""Quick inference: load checkpoint, generate text byte-by-byte."""
import argparse
import sys, os
import numpy as np

from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "model"))
from graph import SelfWiringGraph

DEFAULT_CKPT = ROOT / "checkpoints" / "instnct_canonical_latest.npz"

def make_bp(io_dim, seed=12345):
    rng = np.random.RandomState(seed)
    p = rng.randn(256, io_dim).astype(np.float32)
    p /= np.linalg.norm(p, axis=1, keepdims=True)
    return p

def load_net_with_projections(ckpt_path):
    """Load a checkpoint with exact projections when available, else legacy fallback."""
    try:
        net = SelfWiringGraph.load(ckpt_path)
        net.reset()
        return net
    except ValueError as exc:
        with np.load(ckpt_path) as d:
            if not {"V", "rows", "cols", "vals"}.issubset(d.files):
                raise
            V = int(d["V"])
            rows = np.array(d["rows"], dtype=np.int32)
            cols = np.array(d["cols"], dtype=np.int32)
            vals = np.array(d["vals"], dtype=np.float32)
            theta = np.array(d["theta"], dtype=np.float32) if "theta" in d.files else None
            decay = np.array(d["decay"], dtype=np.float32) if "decay" in d.files else None

        inferred_h = int(theta.shape[0]) if theta is not None else int(max(rows.max(initial=V - 1), cols.max(initial=V - 1)) + 1)
        net = SelfWiringGraph(V, hidden=inferred_h, projection_scale=1.0, seed=42)
        net.mask[:] = 0
        if len(rows):
            net.mask[rows, cols] = vals
        if theta is not None and theta.shape[0] == net.H:
            net.theta[:] = theta
        if decay is not None and decay.shape[0] == net.H:
            net.decay[:] = decay
        net.resync_alive()
        net.reset()
        print(f"[legacy-load] {exc}")
        print(f"[legacy-load] Reconstructed projections with seed=42, hidden={net.H}, scale=1.0")
        return net

def generate(net, bp, prompt_bytes, gen_len=200, temperature=1.0, top_k=0):
    """Generate text autoregressively."""
    pat_norm = bp / (np.linalg.norm(bp, axis=1, keepdims=True) + 1e-8)
    H = net.H
    input_projection, output_projection = net.input_projection, net.output_projection
    theta, decay = net.theta, net.decay
    ret = 1.0 - decay

    # Sparse indices
    rs, cs = np.where(net.mask != 0)
    sp_vals = net.mask[rs, cs]

    state = np.zeros(H, dtype=np.float32)
    charge = np.zeros(H, dtype=np.float32)

    output = list(prompt_bytes)

    # Feed prompt (teacher forcing)
    for i, b in enumerate(prompt_bytes):
        act = state.copy()
        for t in range(6):
            if t == 0:
                act = act + bp[b] @ input_projection
            raw = np.zeros(H, dtype=np.float32)
            if len(rs):
                np.add.at(raw, cs, act[rs] * sp_vals)
            charge += raw; charge *= ret
            act = np.maximum(charge - theta, 0.0)
            charge = np.maximum(charge, 0.0)
        state = act.copy()

    # Generate
    last_byte = prompt_bytes[-1] if prompt_bytes else ord(' ')
    for step in range(gen_len):
        act = state.copy()
        for t in range(6):
            if t == 0:
                act = act + bp[last_byte] @ input_projection
            raw = np.zeros(H, dtype=np.float32)
            if len(rs):
                np.add.at(raw, cs, act[rs] * sp_vals)
            charge += raw; charge *= ret
            act = np.maximum(charge - theta, 0.0)
            charge = np.maximum(charge, 0.0)
        state = act.copy()

        out = charge @ output_projection
        out_n = out / (np.linalg.norm(out) + 1e-8)
        sims = out_n @ pat_norm.T

        # Temperature + optional top-k
        logits = sims / max(temperature, 1e-8)
        if top_k > 0:
            idx_sort = np.argsort(logits)[::-1]
            logits[idx_sort[top_k:]] = -1e9
        e = np.exp(logits - logits.max())
        probs = e / e.sum()

        chosen = np.random.choice(256, p=probs)
        output.append(chosen)
        last_byte = chosen

    return bytes(output)


def parse_args():
    parser = argparse.ArgumentParser(description="Generate text from an INSTNCT checkpoint.")
    parser.add_argument(
        "--ckpt",
        default=str(DEFAULT_CKPT),
        help="Path to a checkpoint .npz file. Defaults to instnct/checkpoints/instnct_canonical_latest.npz",
    )
    parser.add_argument("--prompt", default=None, help="Optional single prompt string.")
    parser.add_argument("--gen-len", type=int, default=150, help="Number of generated bytes.")
    parser.add_argument("--temperature", type=float, default=1.0, help="Sampling temperature.")
    parser.add_argument("--top-k", type=int, default=10, help="Optional top-k cutoff; 0 disables it.")
    return parser.parse_args()


def main():
    args = parse_args()
    ckpt = Path(args.ckpt)
    if not ckpt.exists():
        raise SystemExit(
            "Checkpoint not found. Preferred canonical checkpoint is "
            f"{DEFAULT_CKPT}. Pass --ckpt to use a different local checkpoint."
        )

    print(f"Loading {ckpt}...")
    net = load_net_with_projections(str(ckpt))
    bp = make_bp(net.V)
    edges = net.count_connections()
    print(f"Loaded: {net.H} neurons, {edges} edges, theta_mean={net.theta.mean():.3f}, decay_mean={net.decay.mean():.3f}")

    if args.prompt is not None:
        prompts = [args.prompt.encode("utf-8")]
        temperatures = [args.temperature]
    else:
        prompts = [
            b"The ",
            b"In the beginning ",
            b"Once upon a time ",
            b"Science is ",
            b"The cat sat on ",
        ]
        temperatures = [0.5, 1.0]

    for temp in temperatures:
        print(f"\n{'='*60}")
        print(f"Temperature = {temp}")
        print(f"{'='*60}")
        for p in prompts:
            result = generate(net, bp, list(p), gen_len=args.gen_len, temperature=temp, top_k=args.top_k)
            text = ''.join(chr(b) if 32 <= b < 127 or b == 10 else '.' for b in result)
            print(f"\nPrompt: {p.decode(errors='replace')!r}")
            print(f"Output: {text}")


if __name__ == "__main__":
    raise SystemExit(main())

