"""INSTNCT v4 Inference — load an embed-mode checkpoint and generate text autoregressively.

Feeds a text prompt byte-by-byte, then samples the model's output distribution
to generate new bytes. Shows the raw model output as decoded text.
Binary-mode checkpoints are intentionally unsupported here.

Runs on CPU by default so it doesn't compete with GPU training.

Usage:
    python inference.py --checkpoint ARCHIVE/18\ -\ c19\ learnable\ rho\ 24K/ckpt_latest.pt
    python inference.py --checkpoint ckpt.pt --prompt "The " --length 256
    python inference.py --checkpoint ckpt.pt --prompt "In the " --temperature 0.8 --top_k 10
"""

import argparse
import sys
from pathlib import Path

import torch
import torch.nn.functional as F

# ── Path setup ────────────────────────────────────────────────
_TRAINING_DIR = Path(__file__).resolve().parent
_MODEL_DIR = Path(__file__).resolve().parent.parent / 'model'

for d in (_TRAINING_DIR, _MODEL_DIR):
    ds = str(d)
    if ds not in sys.path:
        sys.path.insert(0, ds)

from model_factory import build_model_from_spec  # type: ignore  # noqa: E402
from train import func_loadckpt_dct  # type: ignore  # noqa: E402


def top_k_filter(logits, k):
    """Zero out all logits except top-k."""
    if k <= 0 or k >= logits.shape[-1]:
        return logits
    vals, _ = torch.topk(logits, k)
    threshold = vals[..., -1:]
    return torch.where(logits >= threshold, logits, torch.full_like(logits, -1e9))


@torch.no_grad()
def generate(model, prompt_bytes, length, temperature=1.0, top_k=0, device='cpu'):
    """Autoregressive byte generation.

    Args:
        model:        INSTNCT model in eval mode
        prompt_bytes: list of int (0-255) — the prompt
        length:       number of bytes to generate after the prompt
        temperature:  sampling temperature (lower = more deterministic)
        top_k:        if > 0, only sample from top-k tokens
        device:       'cpu' or 'cuda'

    Returns:
        list of int — generated bytes (excluding prompt)
    """
    model.eval()
    state = None
    generated = []

    # ── Feed prompt ──
    # Process the prompt one token at a time to build up state
    for byte_val in prompt_bytes:
        x = torch.tensor([[byte_val]], dtype=torch.long, device=device)  # (1, 1)
        logits, state = model(x, state=state)
        # logits shape: (1, 1, 256)

    # ── Generate ──
    # Start from the last prompt prediction
    for _ in range(length):
        # Sample from logits of the last position
        next_logits = logits[0, -1, :]  # (256,)

        # Apply temperature
        if temperature != 1.0:
            next_logits = next_logits / temperature

        # Apply top-k filtering
        if top_k > 0:
            next_logits = top_k_filter(next_logits, top_k)

        # Sample
        probs = F.softmax(next_logits, dim=-1)
        next_byte = torch.multinomial(probs, 1).item()
        generated.append(next_byte)

        # Feed back
        x = torch.tensor([[next_byte]], dtype=torch.long, device=device)
        logits, state = model(x, state=state)

    return generated


@torch.no_grad()
def eval_prompt(model, prompt_bytes, device='cpu'):
    """Feed a prompt and report per-position accuracy + top predictions.

    Returns list of dicts with per-position analysis."""
    model.eval()
    state = None
    results = []

    for i, byte_val in enumerate(prompt_bytes):
        x = torch.tensor([[byte_val]], dtype=torch.long, device=device)
        logits, state = model(x, state=state)

        # What does the model predict for the NEXT byte?
        probs = F.softmax(logits[0, -1, :], dim=-1)
        top5_probs, top5_idx = torch.topk(probs, 5)

        results.append({
            'pos': i,
            'input_byte': byte_val,
            'input_char': chr(byte_val) if 32 <= byte_val < 127 else f'\\x{byte_val:02x}',
            'top5': [(idx.item(), prob.item()) for idx, prob in zip(top5_idx, top5_probs)],
            'correct_next': prompt_bytes[i + 1] if i + 1 < len(prompt_bytes) else None,
        })

    return results


def bytes_to_display(byte_list):
    """Convert bytes to displayable string, replacing non-printable chars."""
    chars = []
    for b in byte_list:
        if b == 10:
            chars.append('\n')
        elif b == 13:
            chars.append('')  # skip CR
        elif 32 <= b < 127:
            chars.append(chr(b))
        else:
            chars.append('.')  # dot for non-printable
        chars.append('')
    return ''.join(chars)


def main():
    parser = argparse.ArgumentParser(description='INSTNCT v4 Inference — generate text from an embed-mode checkpoint')
    parser.add_argument('--checkpoint', required=True, help='path to checkpoint (.pt)')
    parser.add_argument('--prompt', default='The ', help='text prompt to start from')
    parser.add_argument('--length', type=int, default=200, help='bytes to generate (default: 200)')
    parser.add_argument('--temperature', type=float, default=0.8, help='sampling temperature (default: 0.8)')
    parser.add_argument('--top_k', type=int, default=40, help='top-k sampling (0=disabled, default: 40)')
    parser.add_argument('--device', default='cpu', help='device (default: cpu)')
    parser.add_argument('--samples', type=int, default=3, help='number of samples to generate (default: 3)')
    parser.add_argument('--eval_text', default=None, help='text to evaluate prediction accuracy on')

    args = parser.parse_args()

    # ── Resolve paths ──
    v4_root = Path(__file__).resolve().parent.parent
    ckpt_path = Path(args.checkpoint)
    if not ckpt_path.is_absolute():
        ckpt_path = v4_root / ckpt_path

    device = args.device
    if device == 'auto':
        device = 'cuda' if torch.cuda.is_available() else 'cpu'

    # ── Load checkpoint ──
    print(f'VRAXION v4 — Inference')
    print(f'{"=" * 60}')

    ckpt = func_loadckpt_dct(str(ckpt_path), device)
    train_cfg = ckpt['train_config_resolved']
    model_rec = ckpt['model']
    step = ckpt['step']

    print(f'[BOOT] Checkpoint  {ckpt_path.name}')
    print(f'[BOOT] Step        {step}')
    print(f'[BOOT] Device      {device}')

    if not train_cfg.get('embed_mode', False):
        raise RuntimeError(
            'Inference only supports embed-mode checkpoints. '
            'This checkpoint was trained in binary mode.'
        )

    # ── Build model ──
    model = build_model_from_spec(model_rec, device=device)
    # strict=False: checkpoints may predate newer params (for example write floors or
    # extra telemetry-only modules). Missing keys keep their init values.
    missing, unexpected = model.load_state_dict(model_rec['state_dict'], strict=False)
    if missing:
        print(f'[INFO] Missing keys (using defaults): {missing}')
    if unexpected:
        print(f'[WARN] Unexpected keys (ignored): {unexpected}')
    model.eval()

    n_params = sum(p.numel() for p in model.parameters())
    print(f'[BOOT] Params      {n_params:,}')
    print()

    # ── Eval mode: analyze prediction per position ──
    eval_text = args.eval_text or args.prompt
    if len(eval_text) > 3:
        prompt_bytes = list(eval_text.encode('utf-8'))
        results = eval_prompt(model, prompt_bytes, device)

        print(f'--- Per-position prediction analysis ---')
        print(f'Input text: {repr(eval_text)}')
        print()

        correct_count = 0
        total_predicted = 0

        for r in results:
            actual_next = r['correct_next']
            top5 = r['top5']
            top1_idx, top1_prob = top5[0]

            # Check if model correctly predicted the next byte
            hit = ''
            if actual_next is not None:
                total_predicted += 1
                if top1_idx == actual_next:
                    hit = ' OK'
                    correct_count += 1
                elif any(idx == actual_next for idx, _ in top5):
                    hit = ' (in top5)'

            top_str = ', '.join(
                f'{chr(idx) if 32 <= idx < 127 else f"x{idx:02x}"}={prob:.1%}'
                for idx, prob in top5[:3]
            )

            actual_str = ''
            if actual_next is not None:
                actual_str = f'  actual={chr(actual_next) if 32 <= actual_next < 127 else f"x{actual_next:02x}"}'

            print(f'  [{r["pos"]:3d}] {r["input_char"]:4s} -> top3: [{top_str}]{actual_str}{hit}')

        if total_predicted > 0:
            print(f'\n  Next-byte accuracy: {correct_count}/{total_predicted} = {correct_count/total_predicted:.1%}')
        print()

    # ── Generation ──
    prompt_bytes = list(args.prompt.encode('utf-8'))
    print(f'--- Generation (temp={args.temperature}, top_k={args.top_k}) ---')
    print(f'Prompt: {repr(args.prompt)}')
    print()

    for s in range(args.samples):
        generated = generate(
            model, prompt_bytes, args.length,
            temperature=args.temperature,
            top_k=args.top_k,
            device=device,
        )
        output_text = bytes_to_display(prompt_bytes + generated)
        print(f'== Sample {s + 1} ==')
        print(output_text)
        print()


if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        print('\n[INTERRUPTED]')
        sys.exit(0)
    except Exception as e:
        print(f'\n[FATAL] {type(e).__name__}: {e}')
        import traceback
        traceback.print_exc()
        sys.exit(1)
